-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [betree]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Base
import Betree.Types
open Primitives
open betree

/- [betree::betree_utils::load_internal_node]:
   Source: 'src/betree_utils.rs', lines 98:0-98:63 -/
axiom betree_utils.load_internal_node
  : U64 → State → Result (State × (betree.List (U64 × betree.Message)))

/- [betree::betree_utils::store_internal_node]:
   Source: 'src/betree_utils.rs', lines 115:0-115:71 -/
axiom betree_utils.store_internal_node
  :
  U64 → betree.List (U64 × betree.Message) → State → Result (State ×
    Unit)

/- [betree::betree_utils::load_leaf_node]:
   Source: 'src/betree_utils.rs', lines 132:0-132:55 -/
axiom betree_utils.load_leaf_node
  : U64 → State → Result (State × (betree.List (U64 × U64)))

/- [betree::betree_utils::store_leaf_node]:
   Source: 'src/betree_utils.rs', lines 145:0-145:63 -/
axiom betree_utils.store_leaf_node
  : U64 → betree.List (U64 × U64) → State → Result (State × Unit)

