-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [betree]: type definitions
import Base
import Betree.TypesExternal
open Primitives
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace betree

/- [betree::betree::List]
   Source: 'src/betree.rs', lines 17:0-17:23 -/
inductive betree.List (T : Type) :=
| Cons : T → betree.List T → betree.List T
| Nil : betree.List T

/- [betree::betree::UpsertFunState]
   Source: 'src/betree.rs', lines 63:0-63:23 -/
inductive betree.UpsertFunState :=
| Add : U64 → betree.UpsertFunState
| Sub : U64 → betree.UpsertFunState

/- [betree::betree::Message]
   Source: 'src/betree.rs', lines 69:0-69:23 -/
inductive betree.Message :=
| Insert : U64 → betree.Message
| Delete : betree.Message
| Upsert : betree.UpsertFunState → betree.Message

/- [betree::betree::Leaf]
   Source: 'src/betree.rs', lines 167:0-167:11 -/
structure betree.Leaf where
  id : U64
  size : U64

mutual

/- [betree::betree::Internal]
   Source: 'src/betree.rs', lines 156:0-156:15 -/
inductive betree.Internal :=
| mk : U64 → U64 → betree.Node → betree.Node → betree.Internal

/- [betree::betree::Node]
   Source: 'src/betree.rs', lines 179:0-179:9 -/
inductive betree.Node :=
| Internal : betree.Internal → betree.Node
| Leaf : betree.Leaf → betree.Node

end

@[simp, reducible]
def betree.Internal.id (x : betree.Internal) :=
  match x with | betree.Internal.mk x1 _ _ _ => x1

@[simp, reducible]
def betree.Internal.pivot (x : betree.Internal) :=
  match x with | betree.Internal.mk _ x1 _ _ => x1

@[simp, reducible]
def betree.Internal.left (x : betree.Internal) :=
  match x with | betree.Internal.mk _ _ x1 _ => x1

@[simp, reducible]
def betree.Internal.right (x : betree.Internal) :=
  match x with | betree.Internal.mk _ _ _ x1 => x1

/- [betree::betree::Params]
   Source: 'src/betree.rs', lines 187:0-187:13 -/
structure betree.Params where
  min_flush_size : U64
  split_size : U64

/- [betree::betree::NodeIdCounter]
   Source: 'src/betree.rs', lines 201:0-201:20 -/
structure betree.NodeIdCounter where
  next_node_id : U64

/- [betree::betree::BeTree]
   Source: 'src/betree.rs', lines 218:0-218:17 -/
structure betree.BeTree where
  params : betree.Params
  node_id_cnt : betree.NodeIdCounter
  root : betree.Node

end betree
