(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [hashmap]: templates for the decreases clauses *)
module Hashmap.Clauses.Template
open Primitives
open Hashmap.Types

#set-options "--z3rlimit 50 --fuel 1 --ifuel 1"

(** [hashmap::{hashmap::HashMap<T>}::allocate_slots]: decreases clause
    Source: 'tests/src/hashmap.rs', lines 50:4-56:5 *)
unfold
let hashMap_allocate_slots_loop_decreases (t : Type0)
  (slots : alloc_vec_Vec (list_t t)) (n : usize) : nat =
  admit ()

