(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [betree]: external function declarations *)
module Betree.FunsExternal
open Primitives
include Betree.Types

#set-options "--z3rlimit 50 --fuel 1 --ifuel 1"

(** [betree::betree_utils::load_internal_node]:
    Source: 'src/betree_utils.rs', lines 98:0-98:63 *)
val betree_utils_load_internal_node
  : u64 -> state -> result (state & (betree_List_t (u64 & betree_Message_t)))

(** [betree::betree_utils::store_internal_node]:
    Source: 'src/betree_utils.rs', lines 115:0-115:71 *)
val betree_utils_store_internal_node
  :
  u64 -> betree_List_t (u64 & betree_Message_t) -> state -> result (state &
    unit)

(** [betree::betree_utils::load_leaf_node]:
    Source: 'src/betree_utils.rs', lines 132:0-132:55 *)
val betree_utils_load_leaf_node
  : u64 -> state -> result (state & (betree_List_t (u64 & u64)))

(** [betree::betree_utils::store_leaf_node]:
    Source: 'src/betree_utils.rs', lines 145:0-145:63 *)
val betree_utils_store_leaf_node
  : u64 -> betree_List_t (u64 & u64) -> state -> result (state & unit)

