-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [assert_cfg]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace assert_cfg

/-- [assert_cfg::get_b0]:
    Source: 'tests/src/assert-cfg.rs', lines 3:0-5:1 -/
def get_b0 : Result Bool := do
  ok true

/-- [assert_cfg::get_b1]:
    Source: 'tests/src/assert-cfg.rs', lines 7:0-9:1 -/
def get_b1 : Result Bool := do
  ok true

/-- [assert_cfg::f]:
    Source: 'tests/src/assert-cfg.rs', lines 11:0-11:9 -/
def f : Result Unit := do
  ok ()

/-- [assert_cfg::assert_or]:
    Source: 'tests/src/assert-cfg.rs', lines 15:0-18:1
    Visibility: public -/
def assert_or (b0 : Bool) (b1 : Bool) : Result Unit := do
  massert (b0 || b1)
  f

/-- [assert_cfg::assert_and]:
    Source: 'tests/src/assert-cfg.rs', lines 20:0-23:1
    Visibility: public -/
def assert_and (b0 : Bool) (b1 : Bool) : Result Unit := do
  massert b0
  massert b1
  f

/-- [assert_cfg::assert_not_or]:
    Source: 'tests/src/assert-cfg.rs', lines 25:0-28:1
    Visibility: public -/
def assert_not_or (b0 : Bool) (b1 : Bool) : Result Unit := do
  massert (¬ b0)
  massert (¬ b1)
  f

/-- [assert_cfg::assert_not_and]:
    Source: 'tests/src/assert-cfg.rs', lines 30:0-33:1
    Visibility: public -/
def assert_not_and (b0 : Bool) (b1 : Bool) : Result Unit := do
  massert ((¬ b0) || (¬ b1))
  f

/-- [assert_cfg::assert_not_b0_or_b1]:
    Source: 'tests/src/assert-cfg.rs', lines 35:0-38:1
    Visibility: public -/
def assert_not_b0_or_b1 (b0 : Bool) (b1 : Bool) : Result Unit := do
  massert ((¬ b0) || b1)
  f

/-- [assert_cfg::assert_b0_or_not_b1]:
    Source: 'tests/src/assert-cfg.rs', lines 40:0-43:1
    Visibility: public -/
def assert_b0_or_not_b1 (b0 : Bool) (b1 : Bool) : Result Unit := do
  massert (b0 || (¬ b1))
  f

/-- [assert_cfg::assert_not_b0_or_not_b1]:
    Source: 'tests/src/assert-cfg.rs', lines 45:0-48:1
    Visibility: public -/
def assert_not_b0_or_not_b1 (b0 : Bool) (b1 : Bool) : Result Unit := do
  massert ((¬ b0) || (¬ b1))
  f

/-- [assert_cfg::assert_not_b0_and_b1]:
    Source: 'tests/src/assert-cfg.rs', lines 50:0-53:1
    Visibility: public -/
def assert_not_b0_and_b1 (b0 : Bool) (b1 : Bool) : Result Unit := do
  massert (¬ b0)
  massert b1
  f

/-- [assert_cfg::assert_b0_and_not_b1]:
    Source: 'tests/src/assert-cfg.rs', lines 55:0-58:1
    Visibility: public -/
def assert_b0_and_not_b1 (b0 : Bool) (b1 : Bool) : Result Unit := do
  massert b0
  massert (¬ b1)
  f

/-- [assert_cfg::assert_not_b0_and_not_b1]:
    Source: 'tests/src/assert-cfg.rs', lines 60:0-63:1
    Visibility: public -/
def assert_not_b0_and_not_b1 (b0 : Bool) (b1 : Bool) : Result Unit := do
  massert (¬ b0)
  massert (¬ b1)
  f

/-- [assert_cfg::assert_or_call]:
    Source: 'tests/src/assert-cfg.rs', lines 67:0-70:1
    Visibility: public -/
def assert_or_call : Result Unit := do
  let b ← get_b0
  if b
  then ok ()
  else do
       let b1 ← get_b1
       massert b1
  f

/-- [assert_cfg::assert_and_call]:
    Source: 'tests/src/assert-cfg.rs', lines 72:0-75:1
    Visibility: public -/
def assert_and_call : Result Unit := do
  let b ← get_b0
  massert b
  let b1 ← get_b1
  massert b1
  f

/-- [assert_cfg::assert_not_or_call]:
    Source: 'tests/src/assert-cfg.rs', lines 77:0-80:1
    Visibility: public -/
def assert_not_or_call : Result Unit := do
  let b ← get_b0
  massert (¬ b)
  let b1 ← get_b1
  massert (¬ b1)
  f

/-- [assert_cfg::assert_not_and_call]:
    Source: 'tests/src/assert-cfg.rs', lines 82:0-85:1
    Visibility: public -/
def assert_not_and_call : Result Unit := do
  let b ← get_b0
  if b
  then do
       let b1 ← get_b1
       massert (¬ b1)
  else ok ()
  f

/-- [assert_cfg::assert_not_b0_or_b1_call]:
    Source: 'tests/src/assert-cfg.rs', lines 87:0-90:1
    Visibility: public -/
def assert_not_b0_or_b1_call : Result Unit := do
  let b ← get_b0
  if b
  then do
       let b1 ← get_b1
       massert b1
  else ok ()
  f

/-- [assert_cfg::assert_b0_or_not_b1_call]:
    Source: 'tests/src/assert-cfg.rs', lines 92:0-95:1
    Visibility: public -/
def assert_b0_or_not_b1_call : Result Unit := do
  let b ← get_b0
  if b
  then ok ()
  else do
       let b1 ← get_b1
       massert (¬ b1)
  f

/-- [assert_cfg::assert_not_b0_or_not_b1_call]:
    Source: 'tests/src/assert-cfg.rs', lines 97:0-100:1
    Visibility: public -/
def assert_not_b0_or_not_b1_call : Result Unit := do
  let b ← get_b0
  if b
  then do
       let b1 ← get_b1
       massert (¬ b1)
  else ok ()
  f

/-- [assert_cfg::assert_not_b0_and_b1_call]:
    Source: 'tests/src/assert-cfg.rs', lines 102:0-105:1
    Visibility: public -/
def assert_not_b0_and_b1_call : Result Unit := do
  let b ← get_b0
  massert (¬ b)
  let b1 ← get_b1
  massert b1
  f

/-- [assert_cfg::assert_b0_and_not_b1_call]:
    Source: 'tests/src/assert-cfg.rs', lines 107:0-110:1
    Visibility: public -/
def assert_b0_and_not_b1_call : Result Unit := do
  let b ← get_b0
  massert b
  let b1 ← get_b1
  massert (¬ b1)
  f

/-- [assert_cfg::assert_not_b0_and_not_b1_call]:
    Source: 'tests/src/assert-cfg.rs', lines 112:0-115:1
    Visibility: public -/
def assert_not_b0_and_not_b1_call : Result Unit := do
  let b ← get_b0
  massert (¬ b)
  let b1 ← get_b1
  massert (¬ b1)
  f

/-- [assert_cfg::assert_lt]:
    Source: 'tests/src/assert-cfg.rs', lines 119:0-122:1
    Visibility: public -/
def assert_lt (x : Std.U32) : Result Unit := do
  massert (x < 10#u32)
  f

/-- [assert_cfg::assert_le]:
    Source: 'tests/src/assert-cfg.rs', lines 124:0-127:1
    Visibility: public -/
def assert_le (x : Std.U32) : Result Unit := do
  massert (x <= 3494#u32)
  f

/-- [assert_cfg::assert_gt]:
    Source: 'tests/src/assert-cfg.rs', lines 129:0-132:1
    Visibility: public -/
def assert_gt (x : Std.U32) : Result Unit := do
  massert (x > 0#u32)
  f

/-- [assert_cfg::assert_ge]:
    Source: 'tests/src/assert-cfg.rs', lines 134:0-137:1
    Visibility: public -/
def assert_ge (x : Std.U32) : Result Unit := do
  massert (x >= 1#u32)
  f

/-- [assert_cfg::assert_eq]:
    Source: 'tests/src/assert-cfg.rs', lines 139:0-142:1
    Visibility: public -/
def assert_eq (x : Std.U32) : Result Unit := do
  massert (x = 42#u32)
  f

/-- [assert_cfg::assert_ne]:
    Source: 'tests/src/assert-cfg.rs', lines 144:0-147:1
    Visibility: public -/
def assert_ne (x : Std.U32) : Result Unit := do
  massert (x != 0#u32)
  f

/-- [assert_cfg::assert_arith]:
    Source: 'tests/src/assert-cfg.rs', lines 149:0-152:1
    Visibility: public -/
def assert_arith (x : Std.U32) (y : Std.U32) : Result Unit := do
  let i ← x + y
  massert (i < 100#u32)
  f

/-- [assert_cfg::assert_in_loop]: loop body 0:
    Source: 'tests/src/assert-cfg.rs', lines 162:4-165:5 -/
@[rust_loop_body]
def assert_in_loop_loop.body
  (a : Array Std.U32 10#usize) (iter : core.ops.range.Range Std.Usize) :
  Result (ControlFlow (core.ops.range.Range Std.Usize) Unit)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done ())
  | some i =>
    let x ← Array.index_usize a i
    massert (x < 100#u32)
    ok (cont iter1)

/-- [assert_cfg::assert_in_loop]: loop 0:
    Source: 'tests/src/assert-cfg.rs', lines 162:4-165:5 -/
@[rust_loop]
def assert_in_loop_loop
  (iter : core.ops.range.Range Std.Usize) (a : Array Std.U32 10#usize) :
  Result Unit
  := do
  loop
    (fun iter1 => assert_in_loop_loop.body a iter1)
    iter

/-- [assert_cfg::assert_in_loop]:
    Source: 'tests/src/assert-cfg.rs', lines 161:0-166:1 -/
@[reducible]
def assert_in_loop (a : Array Std.U32 10#usize) : Result Unit := do
  assert_in_loop_loop { start := 0#usize, «end» := 10#usize } a

/-- [assert_cfg::assert_or_in_loop]: loop body 0:
    Source: 'tests/src/assert-cfg.rs', lines 173:4-185:5 -/
@[rust_loop_body]
def assert_or_in_loop_loop.body
  (iter : core.ops.range.Range Std.Usize) (a : Array Std.U32 10#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U32
    10#usize)) (Array Std.U32 10#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done a)
  | some i =>
    let c ← Array.index_usize a i
    massert (c < 100#u32)
    let c1 ← lift (core.num.U32.wrapping_sub c 200#u32)
    let i1 ← lift (IScalar.hcast .U32 (-200)#i32)
    let iter2 ←
      do
      massert ((c1 >= i1) || (c1 < 100#u32))
      if c1 >= i1
      then ok iter1
      else ok iter1
    let i2 ← c1 >>> 16#i32
    let i3 ← lift (100#u32 &&& i2)
    let c2 ← lift (core.num.U32.wrapping_add c1 i3)
    let i4 ← lift (IScalar.hcast .U32 (-100)#i32)
    if c2 >= i4
    then ok ()
    else massert (c2 < 100#u32)
    let i5 ← c2 >>> 16#i32
    let i6 ← lift (100#u32 &&& i5)
    let c3 ← lift (core.num.U32.wrapping_add c2 i6)
    massert (c3 < 100#u32)
    let a1 ← Array.update a i c3
    ok (cont (iter2, a1))

/-- [assert_cfg::assert_or_in_loop]: loop 0:
    Source: 'tests/src/assert-cfg.rs', lines 173:4-185:5 -/
@[rust_loop]
def assert_or_in_loop_loop
  (iter : core.ops.range.Range Std.Usize) (a : Array Std.U32 10#usize) :
  Result (Array Std.U32 10#usize)
  := do
  loop
    (fun (iter1, a1) => assert_or_in_loop_loop.body iter1 a1)
    (iter, a)

/-- [assert_cfg::assert_or_in_loop]:
    Source: 'tests/src/assert-cfg.rs', lines 172:0-186:1 -/
@[reducible]
def assert_or_in_loop
  (a : Array Std.U32 10#usize) : Result (Array Std.U32 10#usize) := do
  assert_or_in_loop_loop { start := 0#usize, «end» := 10#usize } a

end assert_cfg
