-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [bool_cmp]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace bool_cmp

/-- [bool_cmp::le]:
    Source: 'tests/src/bool-cmp.rs', lines 5:0-7:1
    Visibility: public -/
def le (a : Bool) (b : Bool) : Result Bool := do
  ok (a <= b)

/-- [bool_cmp::lt]:
    Source: 'tests/src/bool-cmp.rs', lines 9:0-11:1
    Visibility: public -/
def lt (a : Bool) (b : Bool) : Result Bool := do
  ok (a < b)

/-- [bool_cmp::ge]:
    Source: 'tests/src/bool-cmp.rs', lines 13:0-15:1
    Visibility: public -/
def ge (a : Bool) (b : Bool) : Result Bool := do
  ok (a >= b)

/-- [bool_cmp::gt]:
    Source: 'tests/src/bool-cmp.rs', lines 17:0-19:1
    Visibility: public -/
def gt (a : Bool) (b : Bool) : Result Bool := do
  ok (a > b)

end bool_cmp
