-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [constructor_type_annotations]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace constructor_type_annotations

/-- [constructor_type_annotations::test_none]:
    Source: 'tests/src/constructor-type-annotations.rs', lines 12:0-15:1
    Visibility: public -/
def test_none : Result Unit := do
  let b := core.option.Option.is_none (none : Option Std.U32)
  massert b

/- Unit test for [constructor_type_annotations::test_none] -/
#guard (test_none).reducesTo ()

/-- [constructor_type_annotations::test_ok]:
    Source: 'tests/src/constructor-type-annotations.rs', lines 19:0-22:1
    Visibility: public -/
def test_ok : Result Unit := do
  let b ←
    core.result.Result.is_ok (core.result.Result.Ok 2#u32 : core.result.Result
      Std.U32 Std.U32)
  massert b

/- Unit test for [constructor_type_annotations::test_ok] -/
#guard (test_ok).reducesTo ()

/-- [constructor_type_annotations::test_err]:
    Source: 'tests/src/constructor-type-annotations.rs', lines 26:0-29:1
    Visibility: public -/
def test_err : Result Unit := do
  let b ←
    core.result.Result.is_ok (core.result.Result.Err 3#u32 : core.result.Result
      Std.U32 Std.U32)
  massert (¬ b)

/- Unit test for [constructor_type_annotations::test_err] -/
#guard (test_err).reducesTo ()

/-- [constructor_type_annotations::test_some_none]:
    Source: 'tests/src/constructor-type-annotations.rs', lines 33:0-36:1
    Visibility: public -/
def test_some_none : Result Unit := do
  let b := core.option.Option.is_some (some none : Option (Option Std.U32))
  massert b

/- Unit test for [constructor_type_annotations::test_some_none] -/
#guard (test_some_none).reducesTo ()

/-- [constructor_type_annotations::Slot]
    Source: 'tests/src/constructor-type-annotations.rs', lines 38:0-41:1
    Visibility: public -/
@[discriminant isize]
inductive Slot (T : Type) where
| Empty : Slot T
| Full : T → Slot T

/-- [constructor_type_annotations::slot_is_empty]:
    Source: 'tests/src/constructor-type-annotations.rs', lines 43:0-48:1
    Visibility: public -/
def slot_is_empty {T : Type} (s : Slot T) : Result Bool := do
  match s with
  | Slot.Empty => ok true
  | Slot.Full _ => ok false

/-- [constructor_type_annotations::test_slot_empty]:
    Source: 'tests/src/constructor-type-annotations.rs', lines 52:0-55:1
    Visibility: public -/
def test_slot_empty : Result Unit := do
  let b ← slot_is_empty (Slot.Empty : Slot Std.U32)
  massert b

/- Unit test for [constructor_type_annotations::test_slot_empty] -/
#guard (test_slot_empty).reducesTo ()

/-- [constructor_type_annotations::snd_is_none]:
    Source: 'tests/src/constructor-type-annotations.rs', lines 62:0-64:1
    Visibility: public -/
def snd_is_none {T : Type} (p : (Bool × (Option T))) : Result Bool := do
  let (_, o) := p
  ok (core.option.Option.is_none o)

/-- [constructor_type_annotations::test_tuple_none]:
    Source: 'tests/src/constructor-type-annotations.rs', lines 67:0-70:1
    Visibility: public -/
def test_tuple_none : Result Unit := do
  let b ← snd_is_none (true, (none : Option Std.U32))
  massert b

/- Unit test for [constructor_type_annotations::test_tuple_none] -/
#guard (test_tuple_none).reducesTo ()

/-- [constructor_type_annotations::Holder]
    Source: 'tests/src/constructor-type-annotations.rs', lines 72:0-74:1
    Visibility: public -/
structure Holder (T : Type) where
  value : Option T

/-- [constructor_type_annotations::holder_is_none]:
    Source: 'tests/src/constructor-type-annotations.rs', lines 76:0-78:1
    Visibility: public -/
def holder_is_none {T : Type} (h : Holder T) : Result Bool := do
  ok (core.option.Option.is_none h.value)

/-- [constructor_type_annotations::test_struct_none]:
    Source: 'tests/src/constructor-type-annotations.rs', lines 81:0-84:1
    Visibility: public -/
def test_struct_none : Result Unit := do
  let b ← holder_is_none ({ value := none } : Holder Std.U32)
  massert b

/- Unit test for [constructor_type_annotations::test_struct_none] -/
#guard (test_struct_none).reducesTo ()

end constructor_type_annotations
