-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [dyn]
import Aeneas
open Aeneas Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace dyn

/- Trait declaration: [dyn::Trait]
   Source: 'tests/src/dyn.rs', lines 3:0-3:37 -/
structure Trait (Self : Type) where
  get : Self → Result Std.U32

/- [dyn::{dyn::Trait for u32}::get]:
   Source: 'tests/src/dyn.rs', lines 6:4-8:5 -/
def TraitU32.get (self : Std.U32) : Result Std.U32 := do
  ok self

/- Trait implementation: [dyn::{dyn::Trait for u32}]
   Source: 'tests/src/dyn.rs', lines 5:0-9:1 -/
@[reducible]
def TraitU32 : Trait Std.U32 := {
  get := TraitU32.get
}

/- [dyn::{dyn::Trait for bool}::get]:
   Source: 'tests/src/dyn.rs', lines 12:4-14:5 -/
def TraitBool.get (self : Bool) : Result Std.U32 := do
  ok (UScalar.cast_fromBool .U32 self)

/- Trait implementation: [dyn::{dyn::Trait for bool}]
   Source: 'tests/src/dyn.rs', lines 11:0-15:1 -/
@[reducible]
def TraitBool : Trait Bool := {
  get := TraitBool.get
}

/- [dyn::bool_to_trait]:
   Source: 'tests/src/dyn.rs', lines 17:0-19:1 -/
def bool_to_trait (b : Bool) : Result Bool := do
  ok b

/- [dyn::mk_trait]:
   Source: 'tests/src/dyn.rs', lines 21:0-28:1 -/
def mk_trait (b : Bool) : Result (Dyn (fun _dyn => Trait _dyn)) := do
  if b
  then ok (Dyn.mk _ TraitBool true)
  else ok (Dyn.mk _ TraitU32 0#u32)

/- Trait declaration: [dyn::Into]
   Source: 'tests/src/dyn.rs', lines 31:0-33:1 -/
structure Into (Self : Type) (T : Type) where
  into : Self → Result T

/- [dyn::mk_into]:
   Source: 'tests/src/dyn.rs', lines 36:0-43:1 -/
def mk_into
  (U : Type) {V : Type} {T : Type} {W : Type} (IntoInst : Into T V) (IntoInst1
  : Into W V) (b : Bool) (x : T) (y : W) :
  Result (Dyn (fun _dyn => Into _dyn V))
  := do
  if b
  then ok (Dyn.mk _ IntoInst x)
  else ok (Dyn.mk _ IntoInst1 y)

end dyn
