-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [from_to]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace from_to

/- Trait declaration: [from_to::From]
   Source: 'tests/src/from_to.rs', lines 3:0-5:1 -/
structure From (Self : Type) (T : Type) where
  «from» : T → Result Self

/- Trait declaration: [from_to::To]
   Source: 'tests/src/from_to.rs', lines 7:0-11:1 -/
structure To (Self : Type) where
  «to» : forall {T : Type} (FromInst : From T Self), Self → Result T

/- [from_to::{from_to::From<u32> for u32}::from]:
   Source: 'tests/src/from_to.rs', lines 14:4-16:5 -/
def U32.Insts.From_toFromU32.from (x : Std.U32) : Result Std.U32 := do
  ok x

/- Trait implementation: [from_to::{from_to::From<u32> for u32}]
   Source: 'tests/src/from_to.rs', lines 13:0-17:1 -/
@[reducible]
def U32.Insts.From_toFromU32 : From Std.U32 Std.U32 := {
  «from» := U32.Insts.From_toFromU32.from
}

/- [from_to::{from_to::To for u32}::to]:
   Source: 'tests/src/from_to.rs', lines 20:4-22:5 -/
def U32.Insts.From_toTo.to
  {T : Type} (FromTU32Inst : From T Std.U32) (self : Std.U32) : Result T := do
  FromTU32Inst.«from» self

/- Trait implementation: [from_to::{from_to::To for u32}]
   Source: 'tests/src/from_to.rs', lines 19:0-23:1 -/
@[reducible]
def U32.Insts.From_toTo : To Std.U32 := {
  «to» := fun {T : Type} (FromPU32Inst : From T Std.U32) =>
    U32.Insts.From_toTo.to FromPU32Inst
}

end from_to
