-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [implicit_params]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace implicit_params

/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 814:0-814:39
    Name pattern: [core::marker::PhantomData]
    Visibility: public -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- [implicit_params::Holder]
    Source: 'tests/src/implicit-params.rs', lines 8:0-11:1
    Visibility: public -/
@[discriminant isize]
inductive Holder (K : Type) {A : Type} (corecloneCloneInst : core.clone.Clone
  A) where
| Value : K → Holder K corecloneCloneInst
| Phantom : core.marker.PhantomData A → Holder K corecloneCloneInst

/-- [implicit_params::make_value]:
    Source: 'tests/src/implicit-params.rs', lines 13:0-15:1
    Visibility: public -/
def make_value
  {K : Type} {A : Type} (corecloneCloneInst : core.clone.Clone A) (k : K) :
  Result (Holder K corecloneCloneInst)
  := do
  ok (Holder.Value k)

end implicit_params
