-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [issue_767_name_clash]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace issue_767_name_clash

/-- [core::result::{core::result::Result<T, E>}::map]:
    Source: '/rustc/library/core/src/result.rs', lines 832:4-834:53
    Name pattern: [core::result::{core::result::Result<@T, @E>}::map]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::map"]
axiom core.result.Result.map
  {T : Type} {E : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) :
  core.result.Result T E → F → Result (core.result.Result U E)

/-- [issue_767_name_clash::Wrapper]
    Source: 'tests/src/issue-767-name-clash.rs', lines 7:0-7:33
    Visibility: public -/
@[reducible]
def Wrapper := Array Std.U8 32#usize

/-- [issue_767_name_clash::Wrapper]:
    Source: 'tests/src/issue-767-name-clash.rs', lines 7:0-7:33 -/
def Wrapper.constructor (a : Array Std.U8 32#usize) : Result Wrapper := do
  ok a

/-- [issue_767_name_clash::{impl core::ops::function::FnOnce<([u8; 32usize],), issue_767_name_clash::Wrapper> for issue_767_name_clash::Wrapper}::call_once]:
    Source: 'tests/src/issue-767-name-clash.rs', lines 7:0-7:33 -/
def P.Insts.CoreOpsFunctionFnOnceTupleArrayU832Wrapper.call_once
  (state : Array Std.U8 32#usize → Result Wrapper)
  (args : Array Std.U8 32#usize) :
  Result Wrapper
  := do
  Wrapper.constructor args

/-- Trait implementation: [issue_767_name_clash::{impl core::ops::function::FnOnce<([u8; 32usize],), issue_767_name_clash::Wrapper> for issue_767_name_clash::Wrapper}]
    Source: 'tests/src/issue-767-name-clash.rs', lines 7:0-7:33 -/
@[reducible]
def P.Insts.CoreOpsFunctionFnOnceTupleArrayU832Wrapper :
  core.ops.function.FnOnce (Array Std.U8 32#usize → Result Wrapper) (Array
  Std.U8 32#usize) Wrapper := {
  call_once := P.Insts.CoreOpsFunctionFnOnceTupleArrayU832Wrapper.call_once
}

/-- [issue_767_name_clash::make_wrapper]:
    Source: 'tests/src/issue-767-name-clash.rs', lines 9:0-11:1
    Visibility: public -/
def make_wrapper
  (x : core.result.Result (Array Std.U8 32#usize) Unit) :
  Result (core.result.Result Wrapper Unit)
  := do
  core.result.Result.map P.Insts.CoreOpsFunctionFnOnceTupleArrayU832Wrapper x
    (Wrapper.constructor)

end issue_767_name_clash
