-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
module
-- [issue_1206_loop_break]
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace issue_1206_loop_break

/-- [issue_1206_loop_break::first_nonzero]: loop body 0:
    Source: 'tests/src/issue-1206-loop-break.rs', lines 1:0-11:5
    Visibility: public -/
@[rust_loop_body]
def first_nonzero_loop.body
  (xs : Slice Std.U8) (idx : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  :
  Result (ControlFlow (core.ops.range.Range Std.Usize) Std.Usize)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done idx)
  | some i =>
    let i1 ← Slice.index_usize xs i
    if i1 != 0#u8
    then ok (done i)
    else ok (cont iter1)

/-- [issue_1206_loop_break::first_nonzero]: loop 0:
    Source: 'tests/src/issue-1206-loop-break.rs', lines 1:0-11:5
    Visibility: public -/
@[rust_loop]
def first_nonzero_loop
  (iter : core.ops.range.Range Std.Usize) (xs : Slice Std.U8) (idx : Std.Usize)
  :
  Result Std.Usize
  := do
  loop
    (fun iter1 => first_nonzero_loop.body xs idx iter1)
    iter

/-- [issue_1206_loop_break::first_nonzero]:
    Source: 'tests/src/issue-1206-loop-break.rs', lines 4:0-13:1
    Visibility: public -/
def first_nonzero (xs : Slice Std.U8) : Result Std.Usize := do
  let idx := Slice.len xs
  let i := Slice.len xs
  first_nonzero_loop { start := 0#usize, «end» := i } xs idx

end issue_1206_loop_break
