-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [iter_adapters]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace iter_adapters

/-- [iter_adapters::test_enumerate_slice]:
    Source: 'tests/src/iter_adapters.rs', lines 14:0-24:1
    Visibility: public -/
def test_enumerate_slice : Result Unit := do
  let s ←
    lift (Array.to_slice (Array.make 3#usize [ 10#u32, 20#u32, 30#u32 ]))
  let i ← core.slice.Slice.iter s
  let it ← core.slice.iter.IteratorSliceIter.enumerate i
  let (o, it1) ←
    core.iter.adapters.enumerate.IteratorEnumerate.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it
  let (i0, x0) ← core.option.Option.unwrap o
  massert (i0 = 0#usize)
  massert (x0 = 10#u32)
  let (o1, it2) ←
    core.iter.adapters.enumerate.IteratorEnumerate.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it1
  let (i1, x1) ← core.option.Option.unwrap o1
  massert (i1 = 1#usize)
  massert (x1 = 20#u32)
  let (o2, it3) ←
    core.iter.adapters.enumerate.IteratorEnumerate.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it2
  let (i2, x2) ← core.option.Option.unwrap o2
  massert (i2 = 2#usize)
  massert (x2 = 30#u32)
  let (o3, _) ←
    core.iter.adapters.enumerate.IteratorEnumerate.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it3
  let b := core.option.Option.is_none o3
  massert b

/- Unit test for [iter_adapters::test_enumerate_slice] -/
#assert (test_enumerate_slice == ok ())

/-- [iter_adapters::test_enumerate_empty]:
    Source: 'tests/src/iter_adapters.rs', lines 28:0-32:1
    Visibility: public -/
def test_enumerate_empty : Result Unit := do
  let s ← lift (Array.to_slice (Std.Array.empty Std.U32))
  let i ← core.slice.Slice.iter s
  let it ← core.slice.iter.IteratorSliceIter.enumerate i
  let (o, _) ←
    core.iter.adapters.enumerate.IteratorEnumerate.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it
  let b := core.option.Option.is_none o
  massert b

/- Unit test for [iter_adapters::test_enumerate_empty] -/
#assert (test_enumerate_empty == ok ())

/-- [iter_adapters::test_take_2]:
    Source: 'tests/src/iter_adapters.rs', lines 40:0-46:1
    Visibility: public -/
def test_take_2 : Result Unit := do
  let s ←
    lift (Array.to_slice
      (Array.make 4#usize [ 10#u32, 20#u32, 30#u32, 40#u32 ]))
  let i ← core.slice.Slice.iter s
  let it ← core.slice.iter.IteratorSliceIter.take i 2#usize
  let (o, it1) ←
    core.iter.adapters.take.IteratorTake.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it
  let i1 ← core.option.Option.unwrap o
  massert (i1 = 10#u32)
  let (o1, it2) ←
    core.iter.adapters.take.IteratorTake.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it1
  let i2 ← core.option.Option.unwrap o1
  massert (i2 = 20#u32)
  let (o2, _) ←
    core.iter.adapters.take.IteratorTake.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it2
  let b := core.option.Option.is_none o2
  massert b

/- Unit test for [iter_adapters::test_take_2] -/
#assert (test_take_2 == ok ())

/-- [iter_adapters::test_take_0]:
    Source: 'tests/src/iter_adapters.rs', lines 50:0-54:1
    Visibility: public -/
def test_take_0 : Result Unit := do
  let s ←
    lift (Array.to_slice (Array.make 3#usize [ 10#u32, 20#u32, 30#u32 ]))
  let i ← core.slice.Slice.iter s
  let it ← core.slice.iter.IteratorSliceIter.take i 0#usize
  let (o, _) ←
    core.iter.adapters.take.IteratorTake.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it
  let b := core.option.Option.is_none o
  massert b

/- Unit test for [iter_adapters::test_take_0] -/
#assert (test_take_0 == ok ())

/-- [iter_adapters::test_take_more_than_available]:
    Source: 'tests/src/iter_adapters.rs', lines 58:0-65:1
    Visibility: public -/
def test_take_more_than_available : Result Unit := do
  let s ← lift (Array.to_slice (Array.make 3#usize [ 1#u32, 2#u32, 3#u32 ]))
  let i ← core.slice.Slice.iter s
  let it ← core.slice.iter.IteratorSliceIter.take i 5#usize
  let (o, it1) ←
    core.iter.adapters.take.IteratorTake.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it
  let i1 ← core.option.Option.unwrap o
  massert (i1 = 1#u32)
  let (o1, it2) ←
    core.iter.adapters.take.IteratorTake.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it1
  let i2 ← core.option.Option.unwrap o1
  massert (i2 = 2#u32)
  let (o2, it3) ←
    core.iter.adapters.take.IteratorTake.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it2
  let i3 ← core.option.Option.unwrap o2
  massert (i3 = 3#u32)
  let (o3, _) ←
    core.iter.adapters.take.IteratorTake.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it3
  let b := core.option.Option.is_none o3
  massert b

/- Unit test for [iter_adapters::test_take_more_than_available] -/
#assert (test_take_more_than_available == ok ())

/-- [iter_adapters::test_range_u8]: loop body 0:
    Source: 'tests/src/iter_adapters.rs', lines 75:4-77:5
    Visibility: public -/
@[rust_loop_body]
def test_range_u8_loop.body
  (iter : core.ops.range.Range Std.U8) (count : Std.U32) :
  Result (ControlFlow ((core.ops.range.Range Std.U8) × Std.U32) Std.U32)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU8 iter
  match o with
  | none => ok (done count)
  | some _ => let count1 ← count + 1#u32
              ok (cont (iter1, count1))

/-- [iter_adapters::test_range_u8]: loop 0:
    Source: 'tests/src/iter_adapters.rs', lines 75:4-77:5
    Visibility: public -/
@[rust_loop]
def test_range_u8_loop
  (iter : core.ops.range.Range Std.U8) (count : Std.U32) : Result Std.U32 := do
  loop
    (fun (iter1, count1) => test_range_u8_loop.body iter1 count1)
    (iter, count)

/-- [iter_adapters::test_range_u8]:
    Source: 'tests/src/iter_adapters.rs', lines 73:0-79:1
    Visibility: public -/
def test_range_u8 : Result Unit := do
  let count ← test_range_u8_loop { start := 0#u8, «end» := 5#u8 } 0#u32
  massert (count = 5#u32)

/- Unit test for [iter_adapters::test_range_u8] -/
#assert (test_range_u8 == ok ())

/-- [iter_adapters::test_range_u16]: loop body 0:
    Source: 'tests/src/iter_adapters.rs', lines 85:4-87:5
    Visibility: public -/
@[rust_loop_body]
def test_range_u16_loop.body
  (iter : core.ops.range.Range Std.U16) (count : Std.U32) :
  Result (ControlFlow ((core.ops.range.Range Std.U16) × Std.U32) Std.U32)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU16 iter
  match o with
  | none => ok (done count)
  | some _ => let count1 ← count + 1#u32
              ok (cont (iter1, count1))

/-- [iter_adapters::test_range_u16]: loop 0:
    Source: 'tests/src/iter_adapters.rs', lines 85:4-87:5
    Visibility: public -/
@[rust_loop]
def test_range_u16_loop
  (iter : core.ops.range.Range Std.U16) (count : Std.U32) :
  Result Std.U32
  := do
  loop
    (fun (iter1, count1) => test_range_u16_loop.body iter1 count1)
    (iter, count)

/-- [iter_adapters::test_range_u16]:
    Source: 'tests/src/iter_adapters.rs', lines 83:0-89:1
    Visibility: public -/
def test_range_u16 : Result Unit := do
  let count ← test_range_u16_loop { start := 0#u16, «end» := 4#u16 } 0#u32
  massert (count = 4#u32)

/- Unit test for [iter_adapters::test_range_u16] -/
#assert (test_range_u16 == ok ())

/-- [iter_adapters::test_range_u32]: loop body 0:
    Source: 'tests/src/iter_adapters.rs', lines 95:4-97:5
    Visibility: public -/
@[rust_loop_body]
def test_range_u32_loop.body
  (iter : core.ops.range.Range Std.U32) (count : Std.U32) :
  Result (ControlFlow ((core.ops.range.Range Std.U32) × Std.U32) Std.U32)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU32 iter
  match o with
  | none => ok (done count)
  | some _ => let count1 ← count + 1#u32
              ok (cont (iter1, count1))

/-- [iter_adapters::test_range_u32]: loop 0:
    Source: 'tests/src/iter_adapters.rs', lines 95:4-97:5
    Visibility: public -/
@[rust_loop]
def test_range_u32_loop
  (iter : core.ops.range.Range Std.U32) (count : Std.U32) :
  Result Std.U32
  := do
  loop
    (fun (iter1, count1) => test_range_u32_loop.body iter1 count1)
    (iter, count)

/-- [iter_adapters::test_range_u32]:
    Source: 'tests/src/iter_adapters.rs', lines 93:0-99:1
    Visibility: public -/
def test_range_u32 : Result Unit := do
  let count ← test_range_u32_loop { start := 0#u32, «end» := 3#u32 } 0#u32
  massert (count = 3#u32)

/- Unit test for [iter_adapters::test_range_u32] -/
#assert (test_range_u32 == ok ())

/-- [iter_adapters::test_range_u64]: loop body 0:
    Source: 'tests/src/iter_adapters.rs', lines 105:4-107:5
    Visibility: public -/
@[rust_loop_body]
def test_range_u64_loop.body
  (iter : core.ops.range.Range Std.U64) (count : Std.U64) :
  Result (ControlFlow ((core.ops.range.Range Std.U64) × Std.U64) Std.U64)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU64 iter
  match o with
  | none => ok (done count)
  | some _ => let count1 ← count + 1#u64
              ok (cont (iter1, count1))

/-- [iter_adapters::test_range_u64]: loop 0:
    Source: 'tests/src/iter_adapters.rs', lines 105:4-107:5
    Visibility: public -/
@[rust_loop]
def test_range_u64_loop
  (iter : core.ops.range.Range Std.U64) (count : Std.U64) :
  Result Std.U64
  := do
  loop
    (fun (iter1, count1) => test_range_u64_loop.body iter1 count1)
    (iter, count)

/-- [iter_adapters::test_range_u64]:
    Source: 'tests/src/iter_adapters.rs', lines 103:0-109:1
    Visibility: public -/
def test_range_u64 : Result Unit := do
  let count ← test_range_u64_loop { start := 0#u64, «end» := 4#u64 } 0#u64
  massert (count = 4#u64)

/- Unit test for [iter_adapters::test_range_u64] -/
#assert (test_range_u64 == ok ())

/-- [iter_adapters::test_range_usize]: loop body 0:
    Source: 'tests/src/iter_adapters.rs', lines 115:4-117:5
    Visibility: public -/
@[rust_loop_body]
def test_range_usize_loop.body
  (iter : core.ops.range.Range Std.Usize) (count : Std.Usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.Usize)
    Std.Usize)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done count)
  | some _ => let count1 ← count + 1#usize
              ok (cont (iter1, count1))

/-- [iter_adapters::test_range_usize]: loop 0:
    Source: 'tests/src/iter_adapters.rs', lines 115:4-117:5
    Visibility: public -/
@[rust_loop]
def test_range_usize_loop
  (iter : core.ops.range.Range Std.Usize) (count : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun (iter1, count1) => test_range_usize_loop.body iter1 count1)
    (iter, count)

/-- [iter_adapters::test_range_usize]:
    Source: 'tests/src/iter_adapters.rs', lines 113:0-119:1
    Visibility: public -/
def test_range_usize : Result Unit := do
  let count ←
    test_range_usize_loop { start := 0#usize, «end» := 5#usize } 0#usize
  massert (count = 5#usize)

/- Unit test for [iter_adapters::test_range_usize] -/
#assert (test_range_usize == ok ())

/-- [iter_adapters::test_range_empty]: loop body 0:
    Source: 'tests/src/iter_adapters.rs', lines 125:4-127:5
    Visibility: public -/
@[rust_loop_body]
def test_range_empty_loop.body
  (iter : core.ops.range.Range Std.U8) (count : Std.U32) :
  Result (ControlFlow ((core.ops.range.Range Std.U8) × Std.U32) Std.U32)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU8 iter
  match o with
  | none => ok (done count)
  | some _ => let count1 ← count + 1#u32
              ok (cont (iter1, count1))

/-- [iter_adapters::test_range_empty]: loop 0:
    Source: 'tests/src/iter_adapters.rs', lines 125:4-127:5
    Visibility: public -/
@[rust_loop]
def test_range_empty_loop
  (iter : core.ops.range.Range Std.U8) (count : Std.U32) : Result Std.U32 := do
  loop
    (fun (iter1, count1) => test_range_empty_loop.body iter1 count1)
    (iter, count)

/-- [iter_adapters::test_range_empty]:
    Source: 'tests/src/iter_adapters.rs', lines 123:0-129:1
    Visibility: public -/
def test_range_empty : Result Unit := do
  let count ← test_range_empty_loop { start := 5#u8, «end» := 5#u8 } 0#u32
  massert (count = 0#u32)

/- Unit test for [iter_adapters::test_range_empty] -/
#assert (test_range_empty == ok ())

/-- [iter_adapters::test_array_into_iter]:
    Source: 'tests/src/iter_adapters.rs', lines 137:0-144:1
    Visibility: public -/
def test_array_into_iter : Result Unit := do
  let s ←
    lift (Array.to_slice (Array.make 3#usize [ 10#u32, 20#u32, 30#u32 ]))
  let it ← core.slice.Slice.iter s
  let (o, it1) ← core.slice.iter.IteratorSliceIter.next it
  let i ← core.option.Option.unwrap o
  massert (i = 10#u32)
  let (o1, it2) ← core.slice.iter.IteratorSliceIter.next it1
  let i1 ← core.option.Option.unwrap o1
  massert (i1 = 20#u32)
  let (o2, it3) ← core.slice.iter.IteratorSliceIter.next it2
  let i2 ← core.option.Option.unwrap o2
  massert (i2 = 30#u32)
  let (o3, _) ← core.slice.iter.IteratorSliceIter.next it3
  let b := core.option.Option.is_none o3
  massert b

/- Unit test for [iter_adapters::test_array_into_iter] -/
#assert (test_array_into_iter == ok ())

/-- [iter_adapters::test_slice_into_iter]:
    Source: 'tests/src/iter_adapters.rs', lines 148:0-157:1
    Visibility: public -/
def test_slice_into_iter : Result Unit := do
  let s ←
    lift (Array.to_slice (Array.make 4#usize [ 1#u32, 2#u32, 3#u32, 4#u32 ]))
  let it ← core.slice.Slice.iter s
  let (o, it1) ← core.slice.iter.IteratorSliceIter.next it
  let i ← core.option.Option.unwrap o
  massert (i = 1#u32)
  let (o1, it2) ← core.slice.iter.IteratorSliceIter.next it1
  let i1 ← core.option.Option.unwrap o1
  massert (i1 = 2#u32)
  let (o2, it3) ← core.slice.iter.IteratorSliceIter.next it2
  let i2 ← core.option.Option.unwrap o2
  massert (i2 = 3#u32)
  let (o3, it4) ← core.slice.iter.IteratorSliceIter.next it3
  let i3 ← core.option.Option.unwrap o3
  massert (i3 = 4#u32)
  let (o4, _) ← core.slice.iter.IteratorSliceIter.next it4
  let b := core.option.Option.is_none o4
  massert b

/- Unit test for [iter_adapters::test_slice_into_iter] -/
#assert (test_slice_into_iter == ok ())

/-- [iter_adapters::test_enumerate_step_by]:
    Source: 'tests/src/iter_adapters.rs', lines 165:0-172:1
    Visibility: public -/
def test_enumerate_step_by : Result Unit := do
  let s ←
    lift (Array.to_slice
      (Array.make 6#usize [ 10#u32, 20#u32, 30#u32, 40#u32, 50#u32, 60#u32 ]))
  let i ← core.slice.Slice.iter s
  let e ← core.slice.iter.IteratorSliceIter.enumerate i
  let it ←
    core.iter.adapters.enumerate.IteratorEnumerate.step_by
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) e 2#usize
  let (o, it1) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorEnumerate
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)) it
  let (i0, x0) ← core.option.Option.unwrap o
  massert (i0 = 0#usize)
  massert (x0 = 10#u32)
  let (o1, _) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorEnumerate
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)) it1
  let (i1, x1) ← core.option.Option.unwrap o1
  massert (i1 = 2#usize)
  massert (x1 = 30#u32)

/- Unit test for [iter_adapters::test_enumerate_step_by] -/
#assert (test_enumerate_step_by == ok ())

/-- [iter_adapters::test_enumerate_take]:
    Source: 'tests/src/iter_adapters.rs', lines 176:0-184:1
    Visibility: public -/
def test_enumerate_take : Result Unit := do
  let s ←
    lift (Array.to_slice
      (Array.make 5#usize [ 10#u32, 20#u32, 30#u32, 40#u32, 50#u32 ]))
  let i ← core.slice.Slice.iter s
  let e ← core.slice.iter.IteratorSliceIter.enumerate i
  let it ←
    core.iter.adapters.enumerate.IteratorEnumerate.take
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) e 2#usize
  let (o, it1) ←
    core.iter.adapters.take.IteratorTake.next
      (core.iter.traits.iterator.IteratorEnumerate
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)) it
  let (i0, x0) ← core.option.Option.unwrap o
  massert (i0 = 0#usize)
  massert (x0 = 10#u32)
  let (o1, it2) ←
    core.iter.adapters.take.IteratorTake.next
      (core.iter.traits.iterator.IteratorEnumerate
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)) it1
  let (i1, x1) ← core.option.Option.unwrap o1
  massert (i1 = 1#usize)
  massert (x1 = 20#u32)
  let (o2, _) ←
    core.iter.adapters.take.IteratorTake.next
      (core.iter.traits.iterator.IteratorEnumerate
      (core.iter.traits.iterator.IteratorSliceIter Std.U32)) it2
  let b := core.option.Option.is_none o2
  massert b

/- Unit test for [iter_adapters::test_enumerate_take] -/
#assert (test_enumerate_take == ok ())

/-- [iter_adapters::test_take_exhausted_then_next]:
    Source: 'tests/src/iter_adapters.rs', lines 188:0-197:1
    Visibility: public -/
def test_take_exhausted_then_next : Result Unit := do
  let s ← lift (Array.to_slice (Array.make 1#usize [ 42#u32 ]))
  let i ← core.slice.Slice.iter s
  let it ← core.slice.iter.IteratorSliceIter.take i 2#usize
  let (o, it1) ←
    core.iter.adapters.take.IteratorTake.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it
  let i1 ← core.option.Option.unwrap o
  massert (i1 = 42#u32)
  let (o1, it2) ←
    core.iter.adapters.take.IteratorTake.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it1
  let b := core.option.Option.is_none o1
  massert b
  let (o2, _) ←
    core.iter.adapters.take.IteratorTake.next
      (core.iter.traits.iterator.IteratorSliceIter Std.U32) it2
  let b1 := core.option.Option.is_none o2
  massert b1

/- Unit test for [iter_adapters::test_take_exhausted_then_next] -/
#assert (test_take_exhausted_then_next == ok ())

/-- [iter_adapters::test_range_single_element]:
    Source: 'tests/src/iter_adapters.rs', lines 206:0-210:1
    Visibility: public -/
def test_range_single_element : Result Unit := do
  let (o, it) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU8
      { start := 0#u8, «end» := 1#u8 }
  let i ← core.option.Option.unwrap o
  massert (i = 0#u8)
  let (o1, _) ← core.iter.range.IteratorRange.next core.iter.range.StepU8 it
  let b := core.option.Option.is_none o1
  massert b

/- Unit test for [iter_adapters::test_range_single_element] -/
#assert (test_range_single_element == ok ())

/-- [iter_adapters::test_range_u8_near_max]:
    Source: 'tests/src/iter_adapters.rs', lines 214:0-218:1
    Visibility: public -/
def test_range_u8_near_max : Result Unit := do
  let (o, it) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU8
      { start := 254#u8, «end» := 255#u8 }
  let i ← core.option.Option.unwrap o
  massert (i = 254#u8)
  let (o1, _) ← core.iter.range.IteratorRange.next core.iter.range.StepU8 it
  let b := core.option.Option.is_none o1
  massert b

/- Unit test for [iter_adapters::test_range_u8_near_max] -/
#assert (test_range_u8_near_max == ok ())

/-- [iter_adapters::test_range_u8_start_gt_end]:
    Source: 'tests/src/iter_adapters.rs', lines 222:0-225:1
    Visibility: public -/
def test_range_u8_start_gt_end : Result Unit := do
  let (o, _) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU8
      { start := 10#u8, «end» := 5#u8 }
  let b := core.option.Option.is_none o
  massert b

/- Unit test for [iter_adapters::test_range_u8_start_gt_end] -/
#assert (test_range_u8_start_gt_end == ok ())

/-- [iter_adapters::test_range_u8_start_eq_end]:
    Source: 'tests/src/iter_adapters.rs', lines 229:0-232:1
    Visibility: public -/
def test_range_u8_start_eq_end : Result Unit := do
  let (o, _) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU8
      { start := 5#u8, «end» := 5#u8 }
  let b := core.option.Option.is_none o
  massert b

/- Unit test for [iter_adapters::test_range_u8_start_eq_end] -/
#assert (test_range_u8_start_eq_end == ok ())

/-- [iter_adapters::test_range_u16_boundary]:
    Source: 'tests/src/iter_adapters.rs', lines 236:0-242:1
    Visibility: public -/
def test_range_u16_boundary : Result Unit := do
  let (o, it) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU16
      { start := 0#u16, «end» := 3#u16 }
  let i ← core.option.Option.unwrap o
  massert (i = 0#u16)
  let (o1, it1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU16 it
  let i1 ← core.option.Option.unwrap o1
  massert (i1 = 1#u16)
  let (o2, it2) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU16 it1
  let i2 ← core.option.Option.unwrap o2
  massert (i2 = 2#u16)
  let (o3, _) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU16 it2
  let b := core.option.Option.is_none o3
  massert b

/- Unit test for [iter_adapters::test_range_u16_boundary] -/
#assert (test_range_u16_boundary == ok ())

/-- [iter_adapters::test_range_u32_boundary]:
    Source: 'tests/src/iter_adapters.rs', lines 246:0-251:1
    Visibility: public -/
def test_range_u32_boundary : Result Unit := do
  let (o, it) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU32
      { start := 0#u32, «end» := 2#u32 }
  let i ← core.option.Option.unwrap o
  massert (i = 0#u32)
  let (o1, it1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU32 it
  let i1 ← core.option.Option.unwrap o1
  massert (i1 = 1#u32)
  let (o2, _) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU32 it1
  let b := core.option.Option.is_none o2
  massert b

/- Unit test for [iter_adapters::test_range_u32_boundary] -/
#assert (test_range_u32_boundary == ok ())

/-- [iter_adapters::test_range_u64_boundary]:
    Source: 'tests/src/iter_adapters.rs', lines 255:0-261:1
    Visibility: public -/
def test_range_u64_boundary : Result Unit := do
  let (o, it) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU64
      { start := 100#u64, «end» := 103#u64 }
  let i ← core.option.Option.unwrap o
  massert (i = 100#u64)
  let (o1, it1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU64 it
  let i1 ← core.option.Option.unwrap o1
  massert (i1 = 101#u64)
  let (o2, it2) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU64 it1
  let i2 ← core.option.Option.unwrap o2
  massert (i2 = 102#u64)
  let (o3, _) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU64 it2
  let b := core.option.Option.is_none o3
  massert b

/- Unit test for [iter_adapters::test_range_u64_boundary] -/
#assert (test_range_u64_boundary == ok ())

/-- [iter_adapters::test_range_usize_start_gt_end]:
    Source: 'tests/src/iter_adapters.rs', lines 265:0-268:1
    Visibility: public -/
def test_range_usize_start_gt_end : Result Unit := do
  let (o, _) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize
      { start := 10#usize, «end» := 5#usize }
  let b := core.option.Option.is_none o
  massert b

/- Unit test for [iter_adapters::test_range_usize_start_gt_end] -/
#assert (test_range_usize_start_gt_end == ok ())

/-- [iter_adapters::test_step_by_larger_than_range]:
    Source: 'tests/src/iter_adapters.rs', lines 272:0-276:1
    Visibility: public -/
def test_step_by_larger_than_range : Result Unit := do
  let it ←
    core.iter.range.IteratorRange.step_by core.iter.range.StepU8
      { start := 0#u8, «end» := 3#u8 } 10#usize
  let (o, it1) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it
  let i ← core.option.Option.unwrap o
  massert (i = 0#u8)
  let (o1, _) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it1
  let b := core.option.Option.is_none o1
  massert b

/- Unit test for [iter_adapters::test_step_by_larger_than_range] -/
#assert (test_step_by_larger_than_range == ok ())

/-- [iter_adapters::test_step_by_exact_range]:
    Source: 'tests/src/iter_adapters.rs', lines 280:0-284:1
    Visibility: public -/
def test_step_by_exact_range : Result Unit := do
  let it ←
    core.iter.range.IteratorRange.step_by core.iter.range.StepU8
      { start := 0#u8, «end» := 5#u8 } 5#usize
  let (o, it1) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it
  let i ← core.option.Option.unwrap o
  massert (i = 0#u8)
  let (o1, _) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it1
  let b := core.option.Option.is_none o1
  massert b

/- Unit test for [iter_adapters::test_step_by_exact_range] -/
#assert (test_step_by_exact_range == ok ())

/-- [iter_adapters::test_step_by_one]:
    Source: 'tests/src/iter_adapters.rs', lines 288:0-295:1
    Visibility: public -/
def test_step_by_one : Result Unit := do
  let it ←
    core.iter.range.IteratorRange.step_by core.iter.range.StepU8
      { start := 0#u8, «end» := 4#u8 } 1#usize
  let (o, it1) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it
  let i ← core.option.Option.unwrap o
  massert (i = 0#u8)
  let (o1, it2) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it1
  let i1 ← core.option.Option.unwrap o1
  massert (i1 = 1#u8)
  let (o2, it3) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it2
  let i2 ← core.option.Option.unwrap o2
  massert (i2 = 2#u8)
  let (o3, it4) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it3
  let i3 ← core.option.Option.unwrap o3
  massert (i3 = 3#u8)
  let (o4, _) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it4
  let b := core.option.Option.is_none o4
  massert b

/- Unit test for [iter_adapters::test_step_by_one] -/
#assert (test_step_by_one == ok ())

/-- [iter_adapters::test_step_by_empty]:
    Source: 'tests/src/iter_adapters.rs', lines 299:0-302:1
    Visibility: public -/
def test_step_by_empty : Result Unit := do
  let it ←
    core.iter.range.IteratorRange.step_by core.iter.range.StepU8
      { start := 5#u8, «end» := 5#u8 } 3#usize
  let (o, _) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it
  let b := core.option.Option.is_none o
  massert b

/- Unit test for [iter_adapters::test_step_by_empty] -/
#assert (test_step_by_empty == ok ())

/-- [iter_adapters::test_step_by_odd_range]:
    Source: 'tests/src/iter_adapters.rs', lines 306:0-312:1
    Visibility: public -/
def test_step_by_odd_range : Result Unit := do
  let it ←
    core.iter.range.IteratorRange.step_by core.iter.range.StepU8
      { start := 0#u8, «end» := 5#u8 } 2#usize
  let (o, it1) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it
  let i ← core.option.Option.unwrap o
  massert (i = 0#u8)
  let (o1, it2) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it1
  let i1 ← core.option.Option.unwrap o1
  massert (i1 = 2#u8)
  let (o2, it3) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it2
  let i2 ← core.option.Option.unwrap o2
  massert (i2 = 4#u8)
  let (o3, _) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it3
  let b := core.option.Option.is_none o3
  massert b

/- Unit test for [iter_adapters::test_step_by_odd_range] -/
#assert (test_step_by_odd_range == ok ())

/-- [iter_adapters::test_step_by_u8_near_max]:
    Source: 'tests/src/iter_adapters.rs', lines 316:0-322:1
    Visibility: public -/
def test_step_by_u8_near_max : Result Unit := do
  let it ←
    core.iter.range.IteratorRange.step_by core.iter.range.StepU8
      { start := 250#u8, «end» := 255#u8 } 2#usize
  let (o, it1) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it
  let i ← core.option.Option.unwrap o
  massert (i = 250#u8)
  let (o1, it2) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it1
  let i1 ← core.option.Option.unwrap o1
  massert (i1 = 252#u8)
  let (o2, it3) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it2
  let i2 ← core.option.Option.unwrap o2
  massert (i2 = 254#u8)
  let (o3, _) ←
    core.iter.adapters.step_by.IteratorStepBy.next
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU8) it3
  let b := core.option.Option.is_none o3
  massert b

/- Unit test for [iter_adapters::test_step_by_u8_near_max] -/
#assert (test_step_by_u8_near_max == ok ())

/-- [iter_adapters::test_range_inclusive_basic]:
    Source: 'tests/src/iter_adapters.rs', lines 330:0-336:1
    Visibility: public -/
def test_range_inclusive_basic : Result Unit := do
  let it ← core.ops.range.RangeInclusive.new 1#usize 3#usize
  let (o, it1) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.iter.range.StepUsize it
  let i ← core.option.Option.unwrap o
  massert (i = 1#usize)
  let (o1, it2) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.iter.range.StepUsize it1
  let i1 ← core.option.Option.unwrap o1
  massert (i1 = 2#usize)
  let (o2, it3) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.iter.range.StepUsize it2
  let i2 ← core.option.Option.unwrap o2
  massert (i2 = 3#usize)
  let (o3, _) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.iter.range.StepUsize it3
  let b := core.option.Option.is_none o3
  massert b

/- Unit test for [iter_adapters::test_range_inclusive_basic] -/
#assert (test_range_inclusive_basic == ok ())

/-- [iter_adapters::test_range_inclusive_singleton]:
    Source: 'tests/src/iter_adapters.rs', lines 340:0-344:1
    Visibility: public -/
def test_range_inclusive_singleton : Result Unit := do
  let it ← core.ops.range.RangeInclusive.new 7#usize 7#usize
  let (o, it1) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.iter.range.StepUsize it
  let i ← core.option.Option.unwrap o
  massert (i = 7#usize)
  let (o1, _) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.iter.range.StepUsize it1
  let b := core.option.Option.is_none o1
  massert b

/- Unit test for [iter_adapters::test_range_inclusive_singleton] -/
#assert (test_range_inclusive_singleton == ok ())

/-- [iter_adapters::test_range_inclusive_empty]:
    Source: 'tests/src/iter_adapters.rs', lines 348:0-351:1
    Visibility: public -/
def test_range_inclusive_empty : Result Unit := do
  let it ← core.ops.range.RangeInclusive.new 5#usize 3#usize
  let (o, _) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.iter.range.StepUsize it
  let b := core.option.Option.is_none o
  massert b

/- Unit test for [iter_adapters::test_range_inclusive_empty] -/
#assert (test_range_inclusive_empty == ok ())

end iter_adapters
