-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lean_keywords_clash]
import Aeneas
open Aeneas Aeneas.Std RustM ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace lean_keywords_clash

/-- [lean_keywords_clash::end]:
    Source: 'tests/src/lean-keywords-clash.rs', lines 10:0-12:1
    Visibility: public -/
def «end» (x : Std.U32) : RustM Std.U32 := do
  ok x

/-- [lean_keywords_clash::clash]:
    Source: 'tests/src/lean-keywords-clash.rs', lines 14:0-16:1
    Visibility: public -/
def clash (end1 : Std.U32) : RustM Std.U32 := do
  ok end1

/-- [lean_keywords_clash::Rec]
    Source: 'tests/src/lean-keywords-clash.rs', lines 21:0-24:1
    Visibility: public -/
inductive Rec where
| mk : Option Rec → Std.U32 → Rec

def Rec.«end» (x : Rec) := match x with | Rec.mk x1 _ => x1

def Rec.v (x : Rec) := match x with | Rec.mk _ x1 => x1

@[simp]
theorem Rec.«end»._simpLemma_ (end1 : Option Rec) (v : Std.U32) :
  (Rec.mk end1 v).«end» = end1 := by rfl

@[simp]
theorem Rec.v._simpLemma_ (end1 : Option Rec) (v : Std.U32) :
  (Rec.mk end1 v).v = v := by rfl

end lean_keywords_clash
