-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nested_shared_borrows]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace nested_shared_borrows

/-- [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2779:4-2779:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTry.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option
    core.convert.Infallible) T)

/-- [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2793:4-2793:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
  (T : Type) : Option core.convert.Infallible → Result (Option T)

/-- [nested_shared_borrows::do_option]:
    Source: 'tests/src/nested-shared-borrows.rs', lines 12:0-14:1 -/
def do_option : Result (Option Unit) := do
  ok (some ())

/-- [nested_shared_borrows::double_ref_option]:
    Source: 'tests/src/nested-shared-borrows.rs', lines 17:0-20:1
    Visibility: public -/
def double_ref_option (_arg : Std.U8) : Result (Option Unit) := do
  let o ← do_option
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ => ok (some ())
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      Unit residual

/-- [nested_shared_borrows::do_result]:
    Source: 'tests/src/nested-shared-borrows.rs', lines 22:0-24:1 -/
def do_result : Result (core.result.Result Unit Unit) := do
  ok (core.result.Result.Ok ())

/-- [nested_shared_borrows::double_ref_result]:
    Source: 'tests/src/nested-shared-borrows.rs', lines 27:0-30:1
    Visibility: public -/
def double_ref_result
  (_arg : Std.U8) : Result (core.result.Result Unit Unit) := do
  let r ← do_result
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    ok (core.result.Result.Ok ())
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Unit (core.convert.FromSame Unit) residual

/-- [nested_shared_borrows::S]
    Source: 'tests/src/nested-shared-borrows.rs', lines 36:0-38:1
    Visibility: public -/
structure S where
  r : Std.U8

/-- [nested_shared_borrows::f]:
    Source: 'tests/src/nested-shared-borrows.rs', lines 40:0-42:1 -/
def f (x : Std.U8) : Result (core.result.Result Std.U8 Unit) := do
  ok (core.result.Result.Ok x)

/-- [nested_shared_borrows::{nested_shared_borrows::S<'a>}::method_try]:
    Source: 'tests/src/nested-shared-borrows.rs', lines 47:4-50:5
    Visibility: public -/
def S.method_try
  (self : S) (x : Std.U8) : Result (core.result.Result Std.U8 Unit) := do
  let r ← f x
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    ok (core.result.Result.Ok val)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U8 (core.convert.FromSame Unit) residual

/-- [nested_shared_borrows::shared_ref_struct_try]:
    Source: 'tests/src/nested-shared-borrows.rs', lines 54:0-58:1
    Visibility: public -/
def shared_ref_struct_try
  (s : S) (x : Std.U8) : Result (core.result.Result Std.U8 Unit) := do
  let r ← f x
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    ok (core.result.Result.Ok val)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U8 (core.convert.FromSame Unit) residual

/-- [nested_shared_borrows::Owned]
    Source: 'tests/src/nested-shared-borrows.rs', lines 64:0-66:1
    Visibility: public -/
structure Owned where
  r : Std.U8

/-- [nested_shared_borrows::{nested_shared_borrows::Owned}::owned_try]:
    Source: 'tests/src/nested-shared-borrows.rs', lines 70:4-73:5
    Visibility: public -/
def Owned.owned_try
  (self : Owned) (x : Std.U8) : Result (core.result.Result Std.U8 Unit) := do
  let r ← f x
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    ok (core.result.Result.Ok val)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U8 (core.convert.FromSame Unit) residual

/-- [nested_shared_borrows::{nested_shared_borrows::S<'a>}::tailcall]:
    Source: 'tests/src/nested-shared-borrows.rs', lines 78:4-80:5
    Visibility: public -/
def S.tailcall
  (self : S) (x : Std.U8) : Result (core.result.Result Std.U8 Unit) := do
  f x

/-- [nested_shared_borrows::{nested_shared_borrows::S<'a>}::byval]:
    Source: 'tests/src/nested-shared-borrows.rs', lines 83:4-86:5
    Visibility: public -/
def S.byval
  (self : S) (x : Std.U8) : Result (core.result.Result Std.U8 Unit) := do
  let r ← f x
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    ok (core.result.Result.Ok val)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U8 (core.convert.FromSame Unit) residual

end nested_shared_borrows
