-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [switch_test]
import Aeneas
open Aeneas.Std
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace switch_test

/- [switch_test::match_u32]:
   Source: 'tests/src/switch_test.rs', lines 4:0-10:1 -/
def match_u32 (x : U32) : Result U32 :=
  match x with
  | 0#uscalar => Result.ok 0#u32
  | 1#uscalar => Result.ok 1#u32
  | _ => Result.ok 2#u32

end switch_test
