-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [split_files]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace split_files

/-- [split_files::viamacro::Counter]
    Source: 'macrolib/src/lib.rs', lines 8:8-10:9
    Visibility: public -/
structure viamacro.Counter where
  value : Std.U32

/-- [split_files::viamacro::{split_files::viamacro::Counter}::incr]:
    Source: 'macrolib/src/lib.rs', lines 13:12-15:13
    Visibility: public -/
def viamacro.Counter.incr
  (self : viamacro.Counter) : Result viamacro.Counter := do
  let i ← self.value + 1#u32
  ok { value := i }

end split_files
