-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [split_files]
import Aeneas
import SplitFiles.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace split_files

/-- [split_files::ops::sum]:
    Source: 'src/ops.rs', lines 5:0-7:1
    Visibility: public -/
def ops.sum (p : types.Point) : Result Std.I32 := do
  p.x + p.y

end split_files
