import Lean

/-!
# Relevant lines of code, per file and per declaration

An engineering tool, not part of the library.  It answers one question: for each
example of `Aeneas/SLPoC/Tests/Examples`, how much *did the original artifact
cost*, how much does the SLPoC port cost, and how does each of the two split
between computational code and the specification, annotation and proof material
that surrounds it.

Run it from `backends/lean` with

```
lake env lean --run Aeneas/SLPoC/Tests/Examples/scripts/SourceLoc.lean \
  [-o OUT.json] [--html OUT.html] [--manifest FILE] [--cache DIR] [--offline]
```

It reads `Aeneas/SLPoC/Tests/Examples/reports/sources-manifest.json`, downloads
every file it names into a cache (`curl`, once per commit — the manifest pins
one, so the cache never goes stale), and writes the counts twice over:

* `reports/source-loc.json`, the data — `totals`, one `comparisons` entry per
  example, and one `files` entry per file with its `declarations`;
* `reports/source-loc.html`, a standalone page that draws it — no script, style
  or font is fetched from anywhere.  It is regenerated by every run and is not
  committed (`backends/lean/.gitignore`).

A cold run takes about half a minute, a warm one about eight seconds —
elaborating this file.  `--offline` counts only what is already cached.

In the page, every example is one row of three stacked bars — the port, the
artifact it ports, and the unverified Rust reference — drawn to a scale common
to the whole table, so the lengths are comparable between examples as well as
within one.  The bars can be switched to proportions, the rows sorted by size,
by share of specification and proof, or by how much bigger the port is than its
artifact, and filtered by safe-Rust verdict.  Opening a row gives the verdict
and its reason, each file with its link and checksum, and every declaration.  A
closing table lists the twenty declarations that cost the most proof.

Three kinds of file are counted, and each `files` entry says which it is:

* `port` — the Lean file of `Tests/Examples`;
* `source` — the artifact it ports, in Verus, Pulse, Creusot or Rocq;
* `reference` — an *unverified* Rust implementation of roughly the same data
  structure, so that the port can be read against real Rust and not only
  against a verifier's encoding.  A reference costs `code` lines and, being
  unverified, no `spec` or `proof` line at all.

Each `comparisons` entry also carries two verdicts the manifest records.

* `safeRust` — whether the example's program is expressible in the safe Rust
  that Aeneas translates: `yes`, `no`, or `n/a` when no single answer applies —
  the file holds no program, or part of it is safe and the rest is not.  It is a property of the aliasing the example is about, not of its
  proof.
* `coverage` — whether the port answers the whole of its artifact (`full`) or
  deliberately takes a kernel out of a larger file (`fragment`).  A `ratio` is
  emitted only for the first: dividing a kernel by a library would flatter
  whichever side happens to be the fragment, and the totals are taken over the
  comparable examples alone for the same reason.

This supersedes `doubly_linked_loc.py`, which measured one example against one
pinned Verus file.

## Reproducibility

The count is deterministic, and not only from one run to the next on one
machine: the manifest pins every upstream file to a commit and to its SHA-256,
the files to count are read from the manifest in its order rather than from the
directory, nothing is timestamped, no unordered container is iterated, and the
one ranking the report sorts is sorted by a total order.  The same manifest
therefore gives the same numbers anywhere, and a source that changed underneath
it is a checksum mismatch rather than a silent drift.

A run that could not read a file it was told to count says so: `complete` is
false in the JSON, the file is named in `downloadFailures`, and the page carries
a banner.  Counts that are short of something are never presented as if they
were whole.

## What is counted

A line counts when, after its comments have been removed, what is left is at
least four characters wide and is not made of delimiters alone.  Comment-only
lines, blank lines, and lines holding just `}`, `);` or `·` therefore count for
nothing, and a trailing comment costs nothing either.  Import, module, and scope
boilerplate (`import`, `namespace`, `open`, `use`, `mod`, `impl`, `Require`, …)
is dropped too: it is the same in every project and would only measure how many
files a development is split into.  So is a Rust attribute that carries no
verification content — `#[inline]`, `#[derive(…)]`, `#[stable(…)]`,
`#[allow(…)]` — whose density says more about a project's conventions than
about its code; `#[requires(…)]`, `#[verifier::…]` and `#[logic]` are of course
kept, and counted as specification.

Every remaining line is charged to one of three buckets.

* `code` — computational content: what a program does at run time.
* `spec` — what the program is *claimed* to do, and the annotations that make a
  verifier accept it: pre- and postconditions, loop invariants, representation
  predicates, theorem statements, ghost-state definitions, and the attributes
  that register a lemma with the automation.
* `proof` — the justification: tactic scripts, `proof { … }` blocks, `assert`s
  and ghost steps, `Proof. … Qed.`, and Pulse's `fold`/`unfold`/`rewrite`.

`code` is the *computational* half of the question, and `spec + proof` is the
verification half.

## How a line is classified

Each declaration is found by a line-oriented scan (no compiler, no parser: the
sources are Rust, F* and Rocq as well as Lean), and its default bucket comes
from its kind.  Lines inside it are then reclassified by the constructs the
language uses to mix specification into code.

| Language | `code` | `spec` | `proof` |
|---|---|---|---|
| Lean | `def`, `structure`, `inductive` | `theorem`/`lemma` statements, `def`s valued in `IProp`/`Prop`, `@[…]` and `attribute` | tactic blocks after `:= by`, `termination_by`, `decreasing_by` |
| Rust/Verus | `exec fn`, `struct`, `enum` | `spec fn`, `requires`/`ensures`/`decreases`/`invariant` clauses, `Ghost<…>` fields, `#[verifier…]` | `proof fn` bodies, `proof { … }`, `assert`/`assume`/`reveal`/`calc`, `let ghost`, `let tracked` |
| F*/Pulse | `fn` bodies, `let`, `type` | `requires`/`ensures`/`preserves`/`returns`/`invariant`, `slprop`-valued definitions, `#push-options` | `ghost fn`, `Lemma`s, `assert`/`rewrite`/`fold`/`unfold`/`with … .` |
| Rocq/Iris | HeapLang programs (`: expr`, `: val`, `λ:`) | `Lemma`/`Theorem` statements, other `Definition`s, `Notation`, `Ltac` | `Proof. … Qed.` |

The classification is a heuristic and is meant to be read as such: it is
deliberately generous to `code`, so a ratio computed from it understates rather
than overstates the verification overhead.
-/

open Lean

namespace Aeneas.SepLogic.SourceLoc

/-! ## Small string helpers -/

/-- Does `haystack` contain `needle`? -/
def strContains (haystack needle : String) : Bool :=
  if needle.isEmpty then true else (haystack.splitOn needle).length > 1

def containsAny (haystack : String) (needles : List String) : Bool :=
  needles.any (strContains haystack)

def isIdentChar (c : Char) : Bool :=
  c.isAlphanum || c == '_' || c == '\'' || c == '!'

/-- Leading whitespace width. -/
def indentOf (line : String) : Nat :=
  line.toList.takeWhile (fun c => c == ' ' || c == '\t') |>.length

/-- The identifier the line starts with, `""` when it starts with something else. -/
def firstToken (line : String) : String :=
  String.ofList (line.trimAscii.toString.toList.takeWhile isIdentChar)

/-- The identifier-like tokens of a line, in order. -/
partial def tokensOf (line : String) : List String :=
  go line.toList [] []
where
  go (cs cur : List Char) (acc : List String) : List String :=
    match cs with
    | [] => (flush cur acc).reverse
    | c :: rest =>
      if isIdentChar c then go rest (c :: cur) acc else go rest [] (flush cur acc)
  flush (cur : List Char) (acc : List String) : List String :=
    if cur.isEmpty then acc else String.ofList cur.reverse :: acc

/-- The whitespace-separated words of a line. -/
def wordsOf (line : String) : List String :=
  (line.splitOn " ").flatMap (·.splitOn "\t") |>.filter (!·.isEmpty)

/-- A dotted Lean name, `""` when the line does not start with one. -/
def qualifiedToken (line : String) : String :=
  String.ofList (line.trimAscii.toString.toList.takeWhile (fun c => isIdentChar c || c == '.'))

/-- Everything after the `@[…]`, `#[…]` and `[@@…]` attributes a line starts
with, so that `@[simp] theorem foo` is seen to declare a theorem.  Returns the
line unchanged when it starts with no attribute. -/
partial def dropAttributes (line : String) : String :=
  let line := line.trimAscii.toString
  if line.startsWith "@[" || line.startsWith "#[" || line.startsWith "[@@" then
    match skip line.toList 0 false with
    | some rest => dropAttributes (String.ofList rest)
    | none => line
  else line
where
  /-- Drops a bracket group, returning what follows it. -/
  skip (cs : List Char) (depth : Nat) (started : Bool) : Option (List Char) :=
    match cs with
    | [] => none
    | c :: rest =>
      if c == '[' then skip rest (depth + 1) true
      else if c == ']' then
        if depth ≤ 1 then (if started then some rest else none) else skip rest (depth - 1) true
      else skip rest depth started

/-- Everything after the declaration modifiers, so that `pub open spec fn f` is
read as `fn f`.  Delimiters such as the `(crate)` of `pub(crate)` are skipped. -/
partial def dropModifiers (modifiers : List String) (line : String) : String :=
  let line := (dropAttributes line).trimAscii.toString
  let token := firstToken line
  if modifiers.contains token then
    dropModifiers modifiers (line.drop token.length).toString
  else if line.startsWith "(" then
    -- The `(crate)` of `pub(crate)`, the `(super)` of `pub(super)`.
    match skipParens line.toList 0 false with
    | some rest => dropModifiers modifiers (String.ofList rest)
    | none => line
  else line
where
  skipParens (cs : List Char) (depth : Nat) (started : Bool) : Option (List Char) :=
    match cs with
    | [] => none
    | c :: rest =>
      if c == '(' then skipParens rest (depth + 1) true
      else if c == ')' then
        if depth ≤ 1 then (if started then some rest else none)
        else skipParens rest (depth - 1) true
      else skipParens rest depth started

/-- `impl<'a, V> Foo<V> for Bar<V>` without its generic parameters. -/
partial def dropGenerics (line : String) : String :=
  go line.toList 0 []
where
  go (cs : List Char) (depth : Nat) (acc : List Char) : String :=
    match cs with
    | [] => String.ofList acc.reverse
    | c :: rest =>
      if c == '<' then go rest (depth + 1) acc
      else if c == '>' then go rest (depth - 1) (if depth ≤ 1 then ' ' :: acc else acc)
      else if depth > 0 then go rest depth acc
      else go rest depth (c :: acc)

/-- Lines made of delimiters alone carry no content. -/
def isDelimitersOnly (s : String) : Bool :=
  s.toList.all fun c =>
    " \t,;:.(){}[]|·⟨⟩<>=".toList.contains c

/-! ## Comments -/

structure CommentSyntax where
  lineComment : Option String
  blockOpen : String
  blockClose : String
  nested : Bool

inductive Lang where
  | lean | rust | fstar | coq
  deriving Inhabited, BEq, Repr

def Lang.ofString? : String → Option Lang
  | "lean" => some .lean
  | "rust" | "verus" => some .rust
  | "fstar" | "pulse" => some .fstar
  | "coq" | "rocq" => some .coq
  | _ => none

def Lang.toString : Lang → String
  | .lean => "lean" | .rust => "rust" | .fstar => "fstar" | .coq => "coq"

def Lang.commentSyntax : Lang → CommentSyntax
  | .lean => ⟨some "--", "/-", "-/", true⟩
  | .rust => ⟨some "//", "/*", "*/", true⟩
  | .fstar => ⟨some "//", "(*", "*)", true⟩
  | .coq => ⟨none, "(*", "*)", true⟩

def listStartsWith (l : List Char) (s : String) : Bool :=
  s.toList.isPrefixOf l

/-- Removes the comments of one line, given the block-comment depth it starts
at, and returns the depth it ends at.  String literals are preserved, so a `--`
inside one does not open a comment. -/
partial def stripLine (syn : CommentSyntax) (line : String) (depth : Nat) : String × Nat :=
  go line.toList depth false []
where
  go (cs : List Char) (depth : Nat) (inString : Bool) (acc : List Char) : String × Nat :=
    match cs with
    | [] => (String.ofList acc.reverse, depth)
    | c :: rest =>
      if inString then
        if c == '\\' then
          match rest with
          | [] => (String.ofList (c :: acc).reverse, depth)
          | d :: rest' => go rest' depth true (d :: c :: acc)
        else go rest depth (c != '"') (c :: acc)
      else if depth > 0 then
        if listStartsWith (c :: rest) syn.blockClose then
          go (rest.drop (syn.blockClose.length - 1)) (depth - 1) false acc
        else if syn.nested && listStartsWith (c :: rest) syn.blockOpen then
          go (rest.drop (syn.blockOpen.length - 1)) (depth + 1) false acc
        else go rest depth false acc
      else if listStartsWith (c :: rest) syn.blockOpen then
        go (rest.drop (syn.blockOpen.length - 1)) (depth + 1) false acc
      else if syn.lineComment.any (listStartsWith (c :: rest) ·) then
        (String.ofList acc.reverse, depth)
      else go rest depth (c == '"') (c :: acc)

/-- The file, comment-free, one entry per physical line. -/
def stripComments (lang : Lang) (lines : Array String) : Array String := Id.run do
  let syn := lang.commentSyntax
  let mut depth := 0
  let mut out := #[]
  for line in lines do
    let (clean, depth') := stripLine syn line depth
    depth := depth'
    out := out.push clean
  return out

/-! ## Delimiter depth

Used to find where a Rust block or a multi-line proof statement ends. -/

structure Depths where
  braces : Int := 0
  parens : Int := 0
  brackets : Int := 0
  sawOpenBrace : Bool := false

partial def scanDepths (d : Depths) (line : String) : Depths :=
  go line.toList d false
where
  go (cs : List Char) (d : Depths) (inString : Bool) : Depths :=
    match cs with
    | [] => d
    | c :: rest =>
      if inString then
        if c == '\\' then go (rest.drop 1) d true else go rest d (c != '"')
      else if c == '"' then go rest d true
      else
        let d :=
          match c with
          | '{' => { d with braces := d.braces + 1, sawOpenBrace := true }
          | '}' => { d with braces := d.braces - 1 }
          | '(' => { d with parens := d.parens + 1 }
          | ')' => { d with parens := d.parens - 1 }
          | '[' => { d with brackets := d.brackets + 1 }
          | ']' => { d with brackets := d.brackets - 1 }
          | _ => d
        go rest d false

def Depths.open (d : Depths) : Bool :=
  d.braces > 0 || d.parens > 0 || d.brackets > 0

/-! ## Which lines count -/

/-- The name of the attribute a line starts with: `verifier` for
`#[verifier::type_invariant]`, `simp` for `@[simp]`. -/
def attributeName (line : String) : String :=
  let t := line.trimAscii.toString
  let t :=
    if t.startsWith "#![" then (t.drop 3).toString
    else if t.startsWith "#[" || t.startsWith "@[" then (t.drop 2).toString
    else t
  firstToken t

/-- Attributes that carry verification content.  Everything else a Rust file is
decorated with — `#[inline]`, `#[derive(…)]`, `#[stable(…)]`, `#[allow(…)]` — is
metadata, and is not counted at all: it says nothing about either the program or
its proof, and its density says more about a project's conventions than about
its code. -/
def rustVerificationAttributes : List String :=
  ["verifier", "verus", "requires", "ensures", "invariant",
    "invariant_except_break", "invariant_ensures", "decreases", "variant",
    "trigger", "auto", "logic", "predicate", "law", "trusted", "open", "ghost",
    "pure", "terminates", "erasure", "via_fn", "bitwise_proof", "maintains",
    "snapshot", "spec", "sharding", "inductive", "opens_invariants",
    "external_body", "type_invariant", "broadcast", "creusot", "why3"]

def isRustVerificationAttribute (line : String) : Bool :=
  let t := line.trimAscii.toString
  (t.startsWith "#[" || t.startsWith "#![") &&
    rustVerificationAttributes.contains (attributeName t)

/-- An attribute that carries no verification content, and is therefore not
counted. -/
def isPlainAttribute (lang : Lang) (line : String) : Bool :=
  let t := line.trimAscii.toString
  lang == .rust && (t.startsWith "#[" || t.startsWith "#![") &&
    !isRustVerificationAttribute t

/-- Module, import and scope boilerplate: the same in every development, and no
measure of anything. -/
def isBoilerplate (lang : Lang) (line : String) : Bool :=
  let token := firstToken line
  match lang with
  | .lean =>
    ["import", "namespace", "end", "open", "section", "variable", "variables",
      "universe", "set_option", "deriving", "mutual"].contains token
  | .rust =>
    ["use", "mod", "impl", "verus", "extern", "crate"].contains token ||
      (line.trimAscii.toString.startsWith "#!" && !isRustVerificationAttribute line)
  | .fstar =>
    ["module", "open", "include", "friend"].contains token
  | .coq =>
    ["From", "Require", "Import", "Export", "Section", "End", "Context", "Set",
      "Unset", "Open", "Close", "Arguments", "Hint", "Declare", "Existing",
      "Module", "Proof", "Qed", "Defined", "Admitted", "Abort"].contains token

/-- The head of an import, which may span several lines (`use crate::{ … };`). -/
def isImportLine (lang : Lang) (line : String) : Bool :=
  let token := firstToken line
  match lang with
  | .lean => token == "import"
  | .rust => token == "use"
  | .fstar => ["module", "open", "include"].contains token
  | .coq => ["From", "Require", "Import", "Export"].contains token

/-- A line counts when it is at least four characters of something other than
delimiters. -/
def hasContent (clean : String) : Bool :=
  let t := clean.trimAscii.toString
  t.length ≥ 4 && !isDelimitersOnly t

/-- Which lines are boilerplate, the continuation lines of a multi-line import
included. -/
def boilerplateMask (lang : Lang) (clean : Array String) : Array Bool := Id.run do
  let mut mask := clean.map fun l => isBoilerplate lang l.trimAscii.toString
  let mut pending : Option Depths := none
  for i in [0:clean.size] do
    let line := clean[i]!
    if let some d := pending then
      let d := scanDepths d line
      mask := mask.set! i true
      pending := if d.open then some d else none
    else if isImportLine lang line.trimAscii.toString || isPlainAttribute lang line then
      mask := mask.set! i true
      let d := scanDepths {} line
      pending := if d.open then some d else none
  return mask

/-! ## The three buckets -/

inductive Cat where
  | code | spec | proof
  deriving Inhabited, BEq, Repr

def Cat.toString : Cat → String
  | .code => "code" | .spec => "spec" | .proof => "proof"

structure Counts where
  code : Nat := 0
  spec : Nat := 0
  proof : Nat := 0
  deriving Inhabited

def Counts.total (c : Counts) : Nat := c.code + c.spec + c.proof
def Counts.verification (c : Counts) : Nat := c.spec + c.proof

def Counts.add (c : Counts) : Cat → Counts
  | .code => { c with code := c.code + 1 }
  | .spec => { c with spec := c.spec + 1 }
  | .proof => { c with proof := c.proof + 1 }

def Counts.union (a b : Counts) : Counts :=
  ⟨a.code + b.code, a.spec + b.spec, a.proof + b.proof⟩

/-- One declaration: a `def`, a `theorem`, a Rust `fn`, an F* `let`, a Rocq
`Lemma`, … — the "method" a count is reported for. -/
structure Decl where
  name : String
  kind : String
  startLine : Nat
  endLine : Nat
  deriving Inhabited

structure Analysis where
  decls : Array Decl
  /-- Bucket of every physical line, whether it counts or not. -/
  cats : Array Cat
  deriving Inhabited

/-! ## Lean -/

/-- Vocabulary that makes a Lean declaration a specification rather than a
program: the separation logic, and `Prop`. -/
def leanSpecVocabulary : List String :=
  ["IProp", "↦", "∗", "⊢", "-∗", "⦃", "⦄", "emp", "⌜", ": Prop", "→ Prop",
    "IPre", "IPost", "iprop", "Entails"]

def leanDeclKinds : List String :=
  ["def", "abbrev", "theorem", "lemma", "example", "structure", "inductive",
    "class", "instance", "opaque", "axiom", "attribute", "macro", "macro_rules",
    "notation", "syntax", "elab", "infixr", "infixl", "infix", "prefix",
    "postfix", "declare_syntax_cat"]

def leanModifiers : List String :=
  ["private", "protected", "noncomputable", "partial", "unsafe", "scoped",
    "local", "nonrec"]

/-- Declarations proved by a tactic script, whose statement is a specification
and whose body is a proof. -/
def leanProofKinds : List String := ["theorem", "lemma", "example"]

def analyzeLean (clean : Array String) : Analysis := Id.run do
  let n := clean.size
  let mut cats : Array Cat := Array.replicate n .code
  let mut decls : Array Decl := #[]
  -- `§` marks a `section`, so that its `end` does not close a namespace.
  let mut scopes : List String := []
  -- Open declaration: index of its first line, its kind, its name.
  let mut cur : Option (Nat × String × String) := none
  let mut pendingAttr : Option Nat := none
  let mut phase : Cat := .code
  let mut i := 0
  let close := fun (decls : Array Decl) (cur : Option (Nat × String × String)) (stop : Nat) =>
    match cur with
    | none => decls
    | some (start, kind, name) => decls.push ⟨name, kind, start + 1, stop⟩
  while i < n do
    let line := clean[i]!
    let trimmed := line.trimAscii.toString
    let indent := indentOf line
    let token := firstToken trimmed
    if trimmed.isEmpty then
      cats := cats.set! i phase
      i := i + 1
      continue
    let header := dropModifiers leanModifiers trimmed
    let kind := firstToken header
    let isDecl := indent == 0 && leanDeclKinds.contains kind
    if indent == 0 && !isDecl && trimmed.startsWith "@[" then
      -- An attribute on a line of its own belongs to the declaration below it,
      -- and is an annotation in its own right.
      if pendingAttr.isNone then pendingAttr := some i
      cats := cats.set! i .spec
      i := i + 1
      continue
    if indent == 0 && (token == "namespace" || token == "end" || token == "section") then
      decls := close decls cur (pendingAttr.getD i)
      cur := none
      pendingAttr := none
      if token == "namespace" then
        scopes := scopes ++ [(wordsOf trimmed).getD 1 ""]
      else if token == "section" then
        scopes := scopes ++ ["§"]
      else
        scopes := scopes.dropLast
      cats := cats.set! i .code
      i := i + 1
      continue
    if isDecl then
      let start := pendingAttr.getD i
      decls := close decls cur start
      let rest := (header.drop kind.length).toString.trimAscii.toString
      let shortName := if kind == "example" then s!"example@{i + 1}" else qualifiedToken rest
      let shortName := if shortName.isEmpty then s!"{kind}@{i + 1}" else shortName
      let name := String.intercalate "." (scopes.filter (· != "§") ++ [shortName])
      -- The library lives under one namespace; repeating it helps nobody.
      let name := if name.startsWith "Aeneas.SepLogic." then
          (name.drop "Aeneas.SepLogic.".length).toString else name
      cur := some (start, kind, name)
      pendingAttr := none
      phase :=
        if kind == "attribute" then .spec
        else if leanProofKinds.contains kind then .spec
        else if containsAny trimmed leanSpecVocabulary then .spec
        else .code
      cats := cats.set! i phase
      -- A one-line `theorem foo : P := by simp` is statement and proof at once;
      -- charge it to the statement, and everything below it to the proof.
      if leanProofKinds.contains kind &&
          (containsAny trimmed [":= by", ":=by"] || trimmed.endsWith ":=") then
        phase := .proof
      i := i + 1
      continue
    -- A continuation line of the current declaration.
    if cur.isSome then
      let kind := (cur.get!).2.1
      if leanProofKinds.contains kind then
        if phase == .spec then
          cats := cats.set! i .spec
          if containsAny trimmed [":= by", ":=by"] || trimmed.endsWith " by" ||
              trimmed == "by" || trimmed.endsWith ":=" then
            phase := .proof
        else
          cats := cats.set! i .proof
      else if ["termination_by", "decreasing_by"].contains token then
        phase := .proof
        cats := cats.set! i .proof
      else if phase == .proof then
        cats := cats.set! i .proof
      else if trimmed.startsWith "@[" then
        cats := cats.set! i .spec
      else
        let base : Cat :=
          if phase == .code && containsAny trimmed leanSpecVocabulary then .spec else phase
        cats := cats.set! i base
        if trimmed.endsWith " by" || trimmed.endsWith ":= by" then phase := .proof
    else
      cats := cats.set! i .code
    i := i + 1
  decls := close decls cur n
  return ⟨decls, cats⟩

/-! ## Rust and Verus -/

def rustClauseKeywords : List String :=
  ["requires", "ensures", "decreases", "invariant", "invariant_except_break",
    "invariant_ensures", "opens_invariants", "no_unwind", "returns", "when",
    "recommends", "via"]

def rustProofKeywords : List String :=
  ["assert", "assume", "proof", "reveal", "reveal_with_fuel", "calc", "admit",
    "proof_assert!", "snapshot!", "ghost!", "gh!",
    "assert_by_contradiction", "assert_bit_vector", "assert_forall_by",
    "assert_nonlinear_by", "assert_bits_by", "assert_seqs_equal",
    "assert_maps_equal", "assert_sets_equal", "broadcast", "use_type_invariant",
    "axiom", "external_body"]

def rustGhostMarkers : List String :=
  ["let ghost ", "let tracked ", "Ghost(", "Tracked(", "Ghost<", "Tracked<",
    "proof_decl", "spec_affirm", "snapshot!", "proof_assert!", "ghost!"]

/-- Creusot marks its specification functions with an attribute rather than a
`spec fn` modifier. -/
def rustSpecAttributes : List String :=
  ["#[logic]", "#[predicate]", "#[law]", "#[trusted]", "#[open", "#[ghost]",
    "#[pure]", "#[terminates]", "#[bitwise_proof]"]

def rustModifiers : List String :=
  ["pub", "open", "closed", "uninterp", "broadcast", "proof", "spec", "exec",
    "const", "unsafe", "async", "default", "tracked", "ghost", "axiom",
    "atomic", "inline"]

def rustDeclHeads : List String :=
  ["fn", "struct", "enum", "union", "type", "static", "macro_rules!"]

def rustContainerHeads : List String := ["mod", "impl", "trait", "verus"]

/-- Does this line begin a Rust item? -/
def isRustItemStart (line : String) : Bool :=
  let t := line.trimAscii.toString
  t.startsWith "#[" ||
    (rustDeclHeads ++ rustContainerHeads ++ ["use", "broadcast", "global"]).contains
      (firstToken (dropModifiers rustModifiers t))

/-- The last line of the item that starts at `start`.  Counting braces is not
enough — a Verus `ensures` clause may hold a `match … { … }` of its own — so the
end is the closing brace written at the indentation of the item, as every
formatter produces.  An item with no braced body (`uninterp spec fn f(…);`) ends
at the last line before the next item. -/
partial def blockEnd (clean : Array String) (start : Nat) : Nat := Id.run do
  let indent := indentOf clean[start]!
  let mut last := start
  let mut i := start + 1
  while i < clean.size do
    let line := clean[i]!
    let t := line.trimAscii.toString
    if t.isEmpty then
      i := i + 1
      continue
    if indentOf line ≤ indent then
      if t.startsWith "}" then return i
      if isRustItemStart t then return last
    last := i
    i := i + 1
  return clean.size - 1

def rustContainerName (line : String) : String :=
  -- `impl<'a, V> Trait<V> for Foo<V>` names `Foo`; `impl<V> Foo<V>` names `Foo`.
  let toks := tokensOf (dropGenerics line)
  match toks with
  | "impl" :: rest =>
    match rest.dropWhile (· != "for") with
    | _ :: target :: _ => target
    | _ => rest.getD 0 "impl"
  | _ :: name :: _ => name
  | _ => "?"

def analyzeRust (clean : Array String) : Analysis := Id.run do
  let n := clean.size
  let mut cats : Array Cat := Array.replicate n .code
  -- Containers, for qualified names.
  let mut containers : Array (Nat × Nat × String) := #[]
  for i in [0:n] do
    let trimmed := clean[i]!.trimAscii.toString
    let head := firstToken (dropModifiers ["pub"] trimmed)
    if rustContainerHeads.contains head && head != "verus" && strContains trimmed "{" then
      containers := containers.push (i, blockEnd clean i, rustContainerName trimmed)
  -- A first, context-free pass, so that the material that belongs to no
  -- declaration — `broadcast use`, a stray `assert` — is not counted as code.
  for i in [0:n] do
    let t := clean[i]!.trimAscii.toString
    let tok := firstToken t
    if t.startsWith "#[" then cats := cats.set! i .spec
    else if rustProofKeywords.contains tok then cats := cats.set! i .proof
    else if rustClauseKeywords.contains tok then cats := cats.set! i .spec
  let mut decls : Array Decl := #[]
  let mut i := 0
  let mut attrStart : Option Nat := none
  -- An attribute such as `#[ensures(match result { … })]` spans several lines.
  let mut attrDepth : Option Depths := none
  while i < n do
    let line := clean[i]!
    let trimmed := line.trimAscii.toString
    if trimmed.isEmpty then
      i := i + 1
      continue
    if let some d := attrDepth then
      let d := scanDepths d line
      cats := cats.set! i .spec
      attrDepth := if d.open then some d else none
      i := i + 1
      continue
    let header := dropModifiers rustModifiers trimmed
    let head := firstToken header
    let isDecl := rustDeclHeads.contains head
    if !isDecl && (trimmed.startsWith "#[" || trimmed.startsWith "#!") then
      -- An attribute on a line of its own decorates the declaration below it.
      if attrStart.isNone then attrStart := some i
      cats := cats.set! i .spec
      let d := scanDepths {} line
      attrDepth := if d.open then some d else none
      i := i + 1
      continue
    if !isDecl then
      attrStart := none
      i := i + 1
      continue
    let modifiers := tokensOf (dropAttributes trimmed) |>.takeWhile (rustModifiers.contains ·)
    -- Creusot writes `#[logic] fn` where Verus writes `spec fn`.
    let attributes :=
      (clean.extract (attrStart.getD i) (i + 1)).foldl (· ++ " " ++ ·) ""
    let isLogic := containsAny attributes rustSpecAttributes
    let kind :=
      if head != "fn" then head
      else if modifiers.contains "spec" || isLogic then "spec fn"
      else if modifiers.contains "proof" then "proof fn"
      else "exec fn"
    let rest := (header.drop head.length).toString.trimAscii.toString
    let shortName := firstToken rest
    let prefixes := containers.filterMap fun (s, e, nm) =>
      if s < i && i ≤ e then some nm else none
    let name := String.intercalate "::" (prefixes.toList ++ [shortName])
    let stop := blockEnd clean i
    let start := attrStart.getD i
    attrStart := none
    decls := decls.push ⟨name, kind, start + 1, stop + 1⟩
    -- Classify the body.
    let default : Cat :=
      match kind with
      | "spec fn" => .spec
      | "proof fn" => .proof
      | _ => .code
    let mut inClause := false
    let mut proofDepth : Option Depths := none
    for j in [start:stop + 1] do
      let l := clean[j]!
      let t := l.trimAscii.toString
      let tok := firstToken t
      if let some d := proofDepth then
        let d := scanDepths d l
        cats := cats.set! j .proof
        proofDepth := if d.open then some d else none
        continue
      if t.startsWith "#[" then
        cats := cats.set! j .spec
        continue
      if inClause then
        cats := cats.set! j .spec
        if t.endsWith "{" || t == "{" then inClause := false
        continue
      if rustClauseKeywords.contains tok then
        cats := cats.set! j .spec
        if !(t.endsWith "{") then inClause := true
        continue
      if kind != "spec fn" && rustProofKeywords.contains tok then
        cats := cats.set! j .proof
        let d := scanDepths {} l
        if d.open then proofDepth := some d
        continue
      if kind != "spec fn" && containsAny l rustGhostMarkers then
        -- A `Ghost<…>` field declares ghost state; a `let ghost` is a proof step.
        cats := cats.set! j
          (if ["struct", "enum", "union"].contains kind then .spec
           else if default == .code then .proof else default)
        continue
      cats := cats.set! j default
    i := stop + 1
  return ⟨decls, cats⟩

/-! ## F* and Pulse -/

def fstarClauseKeywords : List String :=
  ["requires", "ensures", "preserves", "returns", "opens", "invariant",
    "maintains", "decreases", "ensures_", "requires_"]

def fstarProofKeywords : List String :=
  ["assert", "assume", "rewrite", "fold", "unfold", "with", "show_proof_state",
    "norm", "admit", "calc", "introduce", "eliminate", "slprop_equivs",
    "unfold_with", "fold_with", "later_credit_buy", "dup", "share", "gather",
    "elim", "intro", "drop"]

def fstarDeclHeads : List String :=
  ["let", "val", "fn", "type", "instance", "effect", "exception", "assume",
    "new_effect", "sub_effect", "splice", "class"]

def fstarModifiers : List String :=
  ["inline_for_extraction", "noextract", "noeq", "unopteq", "irreducible",
    "unfold", "private", "abstract", "total", "ghost", "atomic",
    "unobservable", "rec", "assume", "opaque", "logic"]

def analyzeFStar (clean : Array String) : Analysis := Id.run do
  let n := clean.size
  let mut cats : Array Cat := Array.replicate n .code
  -- Declaration starts: column zero, plus the attributes and pragmas above them.
  let mut starts : Array (Nat × Nat × String × String) := #[]
  let mut attrStart : Option Nat := none
  for i in [0:n] do
    let line := clean[i]!
    let trimmed := line.trimAscii.toString
    if trimmed.isEmpty then continue
    if indentOf line != 0 then continue
    if trimmed.startsWith "[@@" || trimmed.startsWith "#push-options" ||
        trimmed.startsWith "#set-options" || trimmed.startsWith "#restart-solver" ||
        trimmed.startsWith "#pop-options" then
      if attrStart.isNone then attrStart := some i
      cats := cats.set! i .spec
      continue
    let toks := tokensOf trimmed
    let header := dropModifiers fstarModifiers trimmed
    let head := firstToken header
    if !fstarDeclHeads.contains head then
      attrStart := none
      continue
    let ghostFn := head == "fn" && toks.contains "ghost"
    let kind :=
      if head == "fn" then "fn"
      else if ghostFn then "ghost fn"
      else if head == "let" && toks.contains "rec" then "let rec"
      else head
    let afterKind := dropModifiers ["let", "val", "fn", "type", "instance",
      "assume", "class", "rec", "and"] header
    let shortName := firstToken afterKind
    let shortName := if shortName.isEmpty then s!"{kind}@{i + 1}" else shortName
    starts := starts.push (attrStart.getD i, i, kind, shortName)
    attrStart := none
  let mut decls : Array Decl := #[]
  for k in [0:starts.size] do
    let (start, headLine, kind, name) := starts[k]!
    let stop := if k + 1 < starts.size then (starts[k + 1]!).1 - 1 else n - 1
    decls := decls.push ⟨name, kind, start + 1, stop + 1⟩
    -- The body of the declaration, in its own right.
    let body := (clean.extract headLine (stop + 1)).foldl (· ++ " " ++ ·) ""
    let default : Cat :=
      if kind == "ghost fn" then .proof
      else if kind == "fn" then .code
      else if containsAny body ["Lemma", "squash "] then .proof
      else if containsAny body ["slprop", "vprop", "prop)", ": prop", "boxable"] then .spec
      else .code
    let mut inClause := false
    let mut proofDepth : Option Depths := none
    for j in [start:stop + 1] do
      let l := clean[j]!
      let t := l.trimAscii.toString
      let tok := firstToken t
      if t.startsWith "[@@" || t.startsWith "#push-options" || t.startsWith "#set-options" ||
          t.startsWith "#restart-solver" || t.startsWith "#pop-options" then
        cats := cats.set! j .spec
        continue
      if let some d := proofDepth then
        let d := scanDepths d l
        cats := cats.set! j .proof
        proofDepth := if d.open then some d else none
        continue
      if inClause then
        cats := cats.set! j .spec
        if t.endsWith "{" || t == "{" then inClause := false
        continue
      if fstarClauseKeywords.contains tok then
        cats := cats.set! j .spec
        if !(t.endsWith "{") then inClause := true
        continue
      if kind == "fn" && fstarProofKeywords.contains tok then
        cats := cats.set! j .proof
        let d := scanDepths {} l
        if d.parens > 0 || d.brackets > 0 then proofDepth := some d
        continue
      cats := cats.set! j default
  return ⟨decls, cats⟩

/-! ## Rocq -/

def coqProofKinds : List String :=
  ["Lemma", "Theorem", "Corollary", "Proposition", "Remark", "Fact", "Instance",
    "Goal"]

def coqDeclHeads : List String :=
  coqProofKinds ++ ["Definition", "Fixpoint", "CoFixpoint", "Inductive",
    "Record", "Notation", "Ltac", "Let", "Class", "Example", "Structure",
    "Variant"]

def coqModifiers : List String :=
  ["Global", "Local", "Program", "Polymorphic", "Monomorphic", "Private",
    "#[local]", "#[global]", "#[export]"]

/-- A Rocq definition is computational when it defines a HeapLang program. -/
def coqProgramMarkers : List String :=
  [": expr", ": val", "λ:", "rec:", ":= (λ:", "#()", "let:"]

def analyzeCoq (clean : Array String) : Analysis := Id.run do
  let n := clean.size
  let mut cats : Array Cat := Array.replicate n .code
  let mut starts : Array (Nat × String × String) := #[]
  for i in [0:n] do
    let line := clean[i]!
    if indentOf line != 0 then continue
    let trimmed := line.trimAscii.toString
    let header := dropModifiers coqModifiers trimmed
    let head := firstToken header
    if !coqDeclHeads.contains head then continue
    let shortName := firstToken (header.drop head.length).toString
    let shortName := if shortName.isEmpty then s!"{head}@{i + 1}" else shortName
    starts := starts.push (i, head, shortName)
  let mut decls : Array Decl := #[]
  for k in [0:starts.size] do
    let (start, kind, name) := starts[k]!
    let stop := if k + 1 < starts.size then (starts[k + 1]!).1 - 1 else n - 1
    decls := decls.push ⟨name, kind, start + 1, stop + 1⟩
    let body := (clean.extract start (stop + 1)).foldl (· ++ " " ++ ·) ""
    let isProgram := containsAny body coqProgramMarkers
    let default : Cat :=
      if coqProofKinds.contains kind then .spec
      else if ["Inductive", "Record", "Structure", "Variant"].contains kind then .code
      else if isProgram then .code
      else .spec
    let mut phase := default
    for j in [start:stop + 1] do
      let t := clean[j]!.trimAscii.toString
      if firstToken t == "Proof" then phase := .proof
      cats := cats.set! j phase
      if ["Qed", "Defined", "Admitted", "Abort"].contains (firstToken t) then phase := default
  return ⟨decls, cats⟩

def analyze (lang : Lang) (clean : Array String) : Analysis :=
  match lang with
  | .lean => analyzeLean clean
  | .rust => analyzeRust clean
  | .fstar => analyzeFStar clean
  | .coq => analyzeCoq clean

/-! ## Counting a file -/

structure DeclReport where
  decl : Decl
  counts : Counts
  deriving Inhabited

structure FileReport where
  /-- `port` for a file of `Tests/Examples`, `source` for the artifact it ports. -/
  role : String
  /-- The example this file belongs to, i.e. the name of the Lean file. -/
  example_ : String
  path : String
  /-- The page a reader should open, with syntax highlighting. -/
  url : Option String
  /-- What was actually downloaded, when that is a different address. -/
  downloadUrl : Option String
  language : Lang
  physicalLines : Nat
  counts : Counts
  /-- Relevant lines that belong to no declaration. -/
  looseCounts : Counts
  sha256 : Option String
  sha256Expected : Option String
  /-- For a reference implementation: whether it is itself safe Rust. -/
  safe : Option Bool
  note : Option String
  decls : Array DeclReport
  deriving Inhabited

def countFile (lang : Lang) (text : String) : Nat × Counts × Counts × Array DeclReport :=
  Id.run do
    let lines := (text.splitOn "\n").toArray
    -- A trailing newline is not a line.
    let lines := if lines.size > 0 && lines[lines.size - 1]! == "" then lines.pop else lines
    let clean := stripComments lang lines
    let ⟨decls, cats⟩ := analyze lang clean
    let mask := boilerplateMask lang clean
    let relevant := clean.mapIdx fun i l => hasContent l && !mask[i]!
    let mut owned : Array Bool := Array.replicate clean.size false
    let mut reports : Array DeclReport := #[]
    for d in decls do
      let mut counts : Counts := {}
      for j in [d.startLine - 1:min d.endLine clean.size] do
        if relevant[j]! then
          counts := counts.add cats[j]!
          owned := owned.set! j true
      if counts.total > 0 then
        reports := reports.push ⟨d, counts⟩
    let mut total : Counts := {}
    let mut loose : Counts := {}
    for j in [0:clean.size] do
      if relevant[j]! then
        total := total.add cats[j]!
        if !owned[j]! then loose := loose.add cats[j]!
    return (lines.size, total, loose, reports)

/-! ## The manifest -/

structure SourceEntry where
  /-- What is downloaded. -/
  url : String
  /-- What a reader should open: the same file with syntax highlighting. -/
  viewUrl : String
  path : String
  language : Lang
  sha256 : Option String
  downloadable : Bool
  reason : Option String
  /-- For a reference implementation: whether it is itself safe Rust. -/
  safe : Option Bool := none
  note : Option String := none
  deriving Inhabited

structure ManifestEntry where
  lean : String
  project : String
  note : Option String
  /-- Whether the example's program can be written in safe Rust, and why. -/
  safeRust : Option (String × String)
  /-- Whether the port answers the whole of the artifact, and why. -/
  coverage : Option (String × String)
  /-- Unverified Rust implementations of roughly the same data structure. -/
  references : Array SourceEntry
  sources : Array SourceEntry
  deriving Inhabited

def jsonStr? (j : Json) (key : String) : Option String :=
  (j.getObjValAs? String key).toOption

def jsonBool? (j : Json) (key : String) : Option Bool :=
  (j.getObjValAs? Bool key).toOption

def jsonArr (j : Json) (key : String) : Array Json :=
  ((j.getObjVal? key).bind Json.getArr?).toOption.getD #[]

def rawUrl (repository commit path : String) : String :=
  s!"https://raw.githubusercontent.com/{repository}/{commit}/{path}"

def blobUrl (repository commit path : String) : String :=
  s!"https://github.com/{repository}/blob/{commit}/{path}"

def parseSources (repos : Json) (owner : String) (entries : Array Json) :
    Except String (Array SourceEntry) := do
  let mut sources : Array SourceEntry := #[]
  for src in entries do
    let downloadable := (jsonBool? src "downloadable").getD true
    let some langName := jsonStr? src "language"
      | throw s!"source of {owner} without a `language`"
    let lang := (Lang.ofString? langName).getD .rust
    let path := (jsonStr? src "path").getD ""
    -- A file is fetched raw and read on its highlighted page; a source given by
    -- an explicit URL is already the page a reader should open.
    let (url, viewUrl) ←
      match jsonStr? src "url" with
      | some url => pure (url, url)
      | none => do
        let some repoKey := jsonStr? src "repo"
          | throw s!"source of {owner} without `repo` or `url`"
        let repo ← repos.getObjVal? repoKey
        let some repository := jsonStr? repo "repository"
          | throw s!"repository {repoKey} without a `repository`"
        let some commit := jsonStr? repo "commit"
          | throw s!"repository {repoKey} without a `commit`"
        pure (rawUrl repository commit path, blobUrl repository commit path)
    sources := sources.push
      { url, viewUrl, path := if path.isEmpty then url else path, language := lang
        sha256 := jsonStr? src "sha256", downloadable
        reason := jsonStr? src "reason", safe := jsonBool? src "safe"
        note := jsonStr? src "note" }
  return sources

def parseManifest (json : Json) : Except String (Array ManifestEntry) := do
  let repos ← json.getObjVal? "repositories"
  let mut entries : Array ManifestEntry := #[]
  for entry in jsonArr json "entries" do
    let some lean := jsonStr? entry "lean"
      | throw "manifest entry without a `lean` field"
    let sources ← parseSources repos lean (jsonArr entry "sources")
    let references ← parseSources repos lean (jsonArr entry "references")
    let verdictOf (field reason : String) : Option (String × String) := do
      let obj ← (entry.getObjVal? field).toOption
      let verdict ← jsonStr? obj "verdict"
      some (verdict, (jsonStr? obj reason).getD "")
    entries := entries.push
      { lean, project := (jsonStr? entry "project").getD "?"
        note := jsonStr? entry "note"
        safeRust := verdictOf "safeRust" "reason"
        coverage := verdictOf "coverage" "note"
        references, sources }
  return entries

/-! ## Downloading -/

def sha256Of (path : System.FilePath) : IO (Option String) := do
  for cmd in ["sha256sum", "shasum"] do
    let args := if cmd == "shasum" then #["-a", "256", path.toString] else #[path.toString]
    let out ← try
        IO.Process.output { cmd, args }
      catch _ => pure { exitCode := 1, stdout := "", stderr := "" }
    if out.exitCode == 0 then
      return (out.stdout.splitOn " ").head?
  return none

/-- Downloads `url` unless it is already cached.  The manifest pins a commit, so
a cached file can never be a stale version of the one that is wanted. -/
def fetch (cache : System.FilePath) (url : String) (offline : Bool) :
    IO (Option System.FilePath) := do
  let key := url.replace "https://raw.githubusercontent.com/" "" |>.replace ":" "_"
  let dest := cache / key
  if ← dest.pathExists then return some dest
  if offline then
    IO.eprintln s!"warning: {url} is not cached and --offline was given"
    return none
  IO.FS.createDirAll (dest.parent.getD cache)
  let out ← IO.Process.output
    { cmd := "curl"
      args := #["-fsSL", "--retry", "3", "--max-time", "120", "-o", dest.toString, url] }
  if out.exitCode != 0 then
    IO.eprintln s!"warning: could not download {url}: {out.stderr}"
    return none
  return some dest

/-! ## The report -/

def countsJson (c : Counts) : Json :=
  Json.mkObj
    [ ("total", toJson c.total), ("code", toJson c.code), ("spec", toJson c.spec),
      ("proof", toJson c.proof), ("verification", toJson c.verification) ]

def optJson : Option String → Json
  | none => Json.null
  | some s => Json.str s

def declJson (d : DeclReport) : Json :=
  Json.mkObj
    [ ("name", Json.str d.decl.name), ("kind", Json.str d.decl.kind),
      ("startLine", toJson d.decl.startLine), ("endLine", toJson d.decl.endLine),
      ("lines", countsJson d.counts) ]

def fileJson (f : FileReport) : Json :=
  Json.mkObj
    [ ("role", Json.str f.role), ("example", Json.str f.example_),
      ("path", Json.str f.path), ("url", optJson f.url),
      ("downloadUrl", optJson f.downloadUrl),
      ("language", Json.str f.language.toString),
      ("physicalLines", toJson f.physicalLines),
      ("lines", countsJson f.counts),
      ("linesOutsideDeclarations", countsJson f.looseCounts),
      ("declarationCount", toJson f.decls.size),
      ("sha256", optJson f.sha256),
      ("sha256Expected", optJson f.sha256Expected),
      ("safeRust", match f.safe with | none => Json.null | some b => Json.bool b),
      ("note", optJson f.note),
      ("sha256Match",
        match f.sha256, f.sha256Expected with
        | some a, some b => Json.bool (a == b)
        | _, _ => Json.null),
      ("declarations", Json.arr (f.decls.map declJson)) ]

def sumCounts (files : Array FileReport) : Counts :=
  files.foldl (fun acc f => acc.union f.counts) {}

/-! ## The HTML view

A standalone page: no script, style or font is fetched from anywhere.  Each
example is one row whose three bars — the port, the artifact it ports, and an
unverified Rust implementation of the same structure — are drawn to a common
scale, so their lengths are comparable across the whole table.  Opening a row
shows the safe-Rust verdict, the files, and every declaration. -/

def escapeHtml (s : String) : String :=
  s |>.replace "&" "&amp;" |>.replace "<" "&lt;" |>.replace ">" "&gt;"
    |>.replace "'" "&#39;"

/-- Renders the light Markdown the manifest's prose uses: `` `code` `` becomes
`<code>`, and `*emphasis*` becomes `<em>`, the latter only outside a code span.
An unbalanced delimiter is left as the character it is. -/
def richText (s : String) : String := Id.run do
  let emphasis (part : String) : String :=
    let pieces := part.splitOn "*"
    if pieces.length % 2 == 0 then part
    else Id.run do
      let mut out := ""
      for i in [0:pieces.length] do
        out := out ++
          (if i == 0 then "" else if i % 2 == 1 then "<em>" else "</em>") ++ pieces[i]!
      return out
  let parts := (escapeHtml s).splitOn "`"
  if parts.length % 2 == 0 then return emphasis (escapeHtml s)
  let mut out := ""
  for i in [0:parts.length] do
    let piece := if i % 2 == 0 then emphasis parts[i]! else parts[i]!
    out := out ++ (if i == 0 then "" else if i % 2 == 1 then "<code>" else "</code>") ++ piece
  return out

/-- A width, as a percentage with one decimal. -/
def widthPct (num den : Nat) : String :=
  if den == 0 then "0%"
  else
    let permille := (1000 * num) / den
    s!"{permille / 10}.{permille % 10}%"

def percent (num den : Nat) : String :=
  if den == 0 then "—" else
    let permille := (2000 * num + den) / (2 * den)
    s!"{permille / 10}.{permille % 10}%"

/-- `×1.23`: how many times the first count is the second. -/
def ratio (num den : Nat) : String :=
  if den == 0 then "—"
  else
    let hundredths := (100 * num + den / 2) / den
    let frac := hundredths % 100
    s!"×{hundredths / 100}.{if frac < 10 then "0" else ""}{frac}"

/-- One stacked bar.  Every segment carries both widths it can be drawn at: its
share of `scale`, for comparison between rows, and its share of its own row, for
comparison of the proportions. -/
def bar (c : Counts) (scale : Nat) : String :=
  let seg (cls label : String) (n : Nat) : String :=
    if n == 0 then "" else
      s!"<span class='seg {cls}' style='--abs:{widthPct n scale};\
        --rel:{widthPct n c.total}' title='{n} {label} lines'></span>"
  if c.total == 0 then "<div class='bar empty' title='not counted'></div>"
  else
    s!"<div class='bar'>{seg "code" "computational" c.code}\
      {seg "spec" "specification" c.spec}{seg "proof" "proof" c.proof}</div>"

/-- `total (code, spec, proof)`, for the cell next to a bar. -/
def countsCell (c : Counts) : String :=
  if c.total == 0 then "<span class='dim'>—</span>"
  else
    s!"<span class='n'>{c.total}</span> <span class='dim'>({c.code} + {c.spec} + \
      {c.proof})</span>"

/-- How a verdict is shown. -/
def verdictLabel : String → String
  | "yes" => "Safe Rust"
  | "no" => "Unsafe Rust"
  | _ => "N/A"

def verdictTitle : String → String
  | "yes" => "expressible in safe Rust"
  | "no" => "needs unsafe Rust"
  | _ => "no single answer applies: no program to write, or safe in part only"

def verdictClass : String → String
  | "yes" => "v-yes"
  | "no" => "v-no"
  | _ => "v-na"

structure ExampleReport where
  name : String
  project : String
  note : Option String
  verdict : String
  reason : String
  coverage : String
  coverageNote : String
  port : Counts
  source : Counts
  reference : Counts
  files : Array FileReport
  deriving Inhabited

def style : String := "
  :root { --code: #0969da; --codebg: #ddf4ff; --spec: #bf8700; --proof: #cf222e;
          --line: #d8dee4; --dim: #6e7781; --panel: #f6f8fa; }
  * { box-sizing: border-box; }
  body { margin: 0 auto; padding: 2rem 1.5rem 6rem; max-width: 76rem; color: #1f2328;
         font: 15px/1.6 -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; }
  h1 { font-size: 1.7rem; margin: 0 0 .5rem; }
  h2 { font-size: 1.25rem; margin: 2.5rem 0 .75rem; padding-bottom: .3rem;
       border-bottom: 1px solid var(--line); }
  h3 { font-size: 1rem; margin: 1.2rem 0 .4rem; }
  p, li { max-width: 62rem; }
  code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 92%; }
  a { color: #0969da; }
  .dim { color: var(--dim); }
  .n { font-variant-numeric: tabular-nums; font-weight: 600; }

  .bar { display: flex; height: .85rem; width: 100%; background: repeating-linear-gradient(
           45deg, #fafbfc, #fafbfc 4px, #f1f3f5 4px, #f1f3f5 8px);
         border-radius: 3px; overflow: hidden; }
  .bar .seg { width: var(--abs); }
  body[data-scale='relative'] .bar .seg { width: var(--rel); }
  .seg.code { background: var(--code); }
  .seg.spec { background: var(--spec); }
  .seg.proof { background: var(--proof); }
  .bar.empty { background: #f1f3f5; }

  .legend { display: flex; gap: 1.2rem; flex-wrap: wrap; align-items: center;
            margin: .5rem 0 1rem; }
  .legend span.key { display: inline-flex; align-items: center; gap: .4rem; }
  .legend i { width: .85rem; height: .85rem; border-radius: 3px; display: inline-block; }

  .controls { display: flex; gap: 1.5rem; flex-wrap: wrap; align-items: center;
              padding: .7rem 1rem; background: var(--panel); border: 1px solid var(--line);
              border-radius: 8px; margin: 1rem 0; }
  .controls label { display: inline-flex; align-items: center; gap: .35rem; }
  .controls fieldset { border: 0; padding: 0; margin: 0; display: flex; gap: .8rem;
                       align-items: center; flex-wrap: wrap; }

  .totals { display: grid; grid-template-columns: 9rem 1fr 15rem; gap: .4rem 1rem;
            align-items: center; margin: 1rem 0; }

  .example { border: 1px solid var(--line); border-radius: 8px; margin: .5rem 0;
             background: #fff; }
  .example[open] { box-shadow: 0 1px 3px rgba(0,0,0,.08); }
  .example > summary { list-style: none; cursor: pointer; padding: .6rem .9rem; }
  .example > summary::-webkit-details-marker { display: none; }
  .example > summary:hover { background: var(--panel); }
  .row { display: grid; grid-template-columns: 16rem 6.5rem 1fr 13rem; gap: .3rem .9rem;
         align-items: center; }
  .row .title { grid-row: span 3; align-self: center; display: flex;
                flex-direction: column; align-items: flex-start; gap: .35rem;
                font-weight: 600; }
  .row .sub { color: var(--dim); font-size: .88em; text-align: right; }
  .filerow { display: grid; grid-template-columns: 8rem 1fr 13rem; gap: .3rem .9rem;
             align-items: center; margin: .3rem 0 .1rem; }
  .badge { justify-self: start; font-size: .78em; font-weight: 700; letter-spacing: .02em;
           padding: .1rem .45rem; border-radius: 999px; text-transform: uppercase; }
  .v-yes { background: #eaf6ec; color: #1a7f37; }
  .v-no { background: #fdecea; color: #b3261e; }
  .v-na { background: #eef1f4; color: var(--dim); }

  .body { padding: .2rem .9rem 1rem; border-top: 1px solid var(--line); }
  .reason { background: var(--panel); border-left: 3px solid var(--line);
            padding: .5rem .8rem; margin: .8rem 0; }
  table { border-collapse: collapse; margin: .4rem 0 1rem; width: 100%; }
  th, td { border-bottom: 1px solid var(--line); padding: .25rem .6rem; text-align: right;
           font-variant-numeric: tabular-nums; }
  th:first-child, td:first-child { text-align: left; }
  th:nth-child(2), td:nth-child(2) { text-align: left; }
  thead th { background: var(--panel); font-size: .85em; }
  td.barcell { width: 30%; }
  details.decls { margin: .3rem 0 1rem; }
  details.decls > summary { cursor: pointer; color: #0969da; font-size: .9em; }
  .filetitle { display: flex; gap: .6rem; align-items: baseline; flex-wrap: wrap;
               margin-top: .9rem; }
  .role { font-size: .75em; font-weight: 700; text-transform: uppercase;
          padding: .05rem .4rem; border-radius: 4px; background: var(--codebg);
          color: #0550ae; }
  .role.source { background: #fff1e5; color: #953800; }
  .role.reference { background: #eef1f4; color: var(--dim); }
  .warning { background: #fdecea; border-left: 3px solid #b3261e; padding: .6rem .8rem;
             border-radius: 4px; }
  .ratio { font-weight: 700; font-variant-numeric: tabular-nums; }
  .frag { font-size: .8em; font-style: italic; color: var(--dim); }
  .unsafe { font-size: .8em; color: #b3261e; }
  .safe { font-size: .8em; color: #1a7f37; }
  body[data-hide~='yes'] .example[data-verdict='yes'],
  body[data-hide~='no'] .example[data-verdict='no'],
  body[data-hide~='na'] .example[data-verdict='na'] { display: none; }
"

def script : String := "
  const body = document.body, list = document.getElementById('examples');
  const rows = Array.from(list.children);
  document.getElementById('scale').addEventListener('change', e => {
    body.dataset.scale = e.target.value;
  });
  const keys = {
    name: r => r.dataset.name.toLowerCase(),
    port: r => -Number(r.dataset.port),
    proof: r => -Number(r.dataset.proofshare),
    source: r => -Number(r.dataset.source),
    ratio: r => -Number(r.dataset.ratio)
  };
  document.getElementById('sort').addEventListener('change', e => {
    const key = keys[e.target.value];
    rows.slice().sort((a, b) => {
      const x = key(a), y = key(b);
      return x < y ? -1 : x > y ? 1 : 0;
    }).forEach(r => list.appendChild(r));
  });
  function hidden() {
    return Array.from(document.querySelectorAll('input[name=verdict]'))
      .filter(i => !i.checked).map(i => i.value).join(' ');
  }
  for (const input of document.querySelectorAll('input[name=verdict]'))
    input.addEventListener('change', () => { body.dataset.hide = hidden(); });
  document.getElementById('expand').addEventListener('click', () => {
    const open = rows.some(r => !r.open);
    rows.forEach(r => { r.open = open; });
  });
"


/-- The declaration table of one file. -/
def renderDecls (f : FileReport) : String := Id.run do
  if f.decls.isEmpty then return ""
  let scale := f.decls.foldl (fun m d => max m d.counts.total) 1
  let mut out := s!"<details class='decls'><summary>{f.decls.size} declarations</summary>\
    <table><thead><tr><th>Declaration</th><th>Kind</th><th>Lines</th>\
    <th>Code</th><th>Spec</th><th>Proof</th><th class='barcell'></th></tr></thead><tbody>"
  for d in f.decls do
    out := out ++ s!"<tr><td><code>{escapeHtml d.decl.name}</code></td>\
      <td class='dim'>{escapeHtml d.decl.kind}</td><td class='n'>{d.counts.total}</td>\
      <td>{d.counts.code}</td><td>{d.counts.spec}</td><td>{d.counts.proof}</td>\
      <td class='barcell'>{bar d.counts scale}</td></tr>"
  return out ++ "</tbody></table></details>"

def renderFile (f : FileReport) : String := Id.run do
  let name :=
    match f.url with
    | some url => s!"<a href='{escapeHtml url}'><code>{escapeHtml f.path}</code></a>"
    | none => s!"<code>{escapeHtml f.path}</code>"
  let safety :=
    match f.safe with
    | some true => "<span class='safe'>safe Rust</span>"
    | some false => "<span class='unsafe'>uses <code>unsafe</code></span>"
    | none => ""
  let mut out := s!"<div class='filetitle'><span class='role {f.role}'>{f.role}</span>\
    {name} <span class='dim'>{f.language.toString}, {f.physicalLines} physical lines</span> \
    {safety}</div>"
  if let some note := f.note then
    out := out ++ s!"<p class='dim'>{richText note}</p>"
  out := out ++ s!"<div class='filerow'><span class='sub'>relevant</span>\
    <span>{bar f.counts (max f.counts.total 1)}</span>\
    <span>{countsCell f.counts}</span></div>\
    <p class='dim'>{percent f.counts.verification f.counts.total} of it is \
    specification and proof.</p>"
  return out ++ renderDecls f

def renderExample (e : ExampleReport) (scale : Nat) : String := Id.run do
  let verdictKey := if e.verdict == "n/a" then "na" else e.verdict
  let proofShare := 1000 * e.port.verification / max e.port.total 1
  let comparable := e.coverage == "full" && e.source.total > 0
  -- How much bigger the verified port is than the artifact it ports.  A port
  -- that answers only a fragment of its artifact sorts last: dividing the two
  -- would compare a kernel against a library.
  let ratioKey := if comparable then 1000 * e.port.total / e.source.total else 0
  let mut out := s!"<details class='example' data-verdict='{verdictKey}' \
    data-name='{escapeHtml e.name}' data-port='{e.port.total}' \
    data-source='{e.source.total}' data-proofshare='{proofShare}' data-ratio='{ratioKey}'>\
    <summary><div class='row'>\
    <span class='title'><code>{escapeHtml e.name}</code>\
    <span class='badge {verdictClass e.verdict}' title='{verdictTitle e.verdict}'>\
    {verdictLabel e.verdict}</span></span>"
  let line (label title : String) (c : Counts) (tag : String) : String :=
    s!"<span class='sub' title='{title}'>{label}</span><span>{bar c scale}</span>\
      <span>{countsCell c} {tag}</span>"
  -- How this port compares with the artifact above it, when the two compare.
  let portTag :=
    if e.source.total == 0 then ""
    else if comparable then
      s!"<span class='ratio' title='the port divided by the artifact above'>\
        {ratio e.port.total e.source.total}</span>"
    else "<span class='frag' title='the port answers part of that file, so the two \
      are not a ratio'>fragment</span>"
  out := out ++
    line "artifact" "the file this port answers" e.source "" ++
    line "Aeneas+SL" "this port" e.port portTag ++
    line "Rust" "an unverified Rust implementation of the same structure"
      e.reference ""
  out := out ++ "</div></summary><div class='body'>"
  if let some note := e.note then
    out := out ++ s!"<p>{richText note}</p>"
  out := out ++ s!"<p class='reason'><strong>{verdictLabel e.verdict}</strong> — \
    {richText e.reason}</p>"
  if e.source.total > 0 then
    out := out ++ s!"<p class='reason'><strong>Covers the artifact: \
      {escapeHtml e.coverage}</strong> — {richText e.coverageNote}</p>"
  for f in e.files do
    out := out ++ renderFile f
  return out ++ "</div></details>"

/-- The declarations that cost the most proof, over every port. -/
def renderHotspots (files : Array FileReport) : String := Id.run do
  let mut all : Array (String × DeclReport) := #[]
  for f in files do
    if f.role == "port" then
      for d in f.decls do
        if d.counts.proof > 0 then all := all.push (f.example_, d)
  -- A total order, so that the ranking never depends on how the sort breaks a tie.
  let sorted := all.qsort fun a b =>
    if a.2.counts.proof != b.2.counts.proof then a.2.counts.proof > b.2.counts.proof
    else if a.2.counts.total != b.2.counts.total then a.2.counts.total > b.2.counts.total
    else if a.1 != b.1 then a.1 < b.1
    else a.2.decl.name < b.2.decl.name
  let top := sorted.extract 0 (min 20 sorted.size)
  if top.isEmpty then return ""
  let scale := top.foldl (fun m (_, d) => max m d.counts.total) 1
  let mut out := "<h2>Where the proof lines are</h2><p>The twenty declarations of \
    the ports that cost the most proof.</p><table><thead><tr><th>Declaration</th>\
    <th>Example</th><th>Lines</th><th>Code</th><th>Spec</th><th>Proof</th>\
    <th class='barcell'></th></tr></thead><tbody>"
  for (example_, d) in top do
    out := out ++ s!"<tr><td><code>{escapeHtml d.decl.name}</code></td>\
      <td class='dim'>{escapeHtml example_}</td><td class='n'>{d.counts.total}</td>\
      <td>{d.counts.code}</td><td>{d.counts.spec}</td>\
      <td class='n'>{d.counts.proof}</td>\
      <td class='barcell'>{bar d.counts scale}</td></tr>"
  return out ++ "</tbody></table>"

def renderHtml (examples : Array ExampleReport) (files : Array FileReport)
    (manifest : String) (failures : Array String) : String := Id.run do
  let ports := files.filter (·.role == "port")
  let sources := files.filter (·.role == "source")
  let references := files.filter (·.role == "reference")
  let scale := examples.foldl
    (fun m e => max m (max e.port.total (max e.source.total e.reference.total))) 1
  let count (verdict : String) : Nat := (examples.filter (·.verdict == verdict)).size
  let mut out := s!"<!DOCTYPE html>\n<html lang='en'><head><meta charset='utf-8'>\
    <meta name='viewport' content='width=device-width, initial-scale=1'>\
    <title>SLPoC — lines of code against the original artifacts</title>\
    <style>{style}</style></head><body data-scale='absolute' data-hide=''>"
  out := out ++ "<h1>Lines of code against the original artifacts</h1>"
  unless failures.isEmpty do
    out := out ++ s!"<p class='warning'><strong>This run is incomplete.</strong> \
      {failures.size} file(s) the manifest names could not be read, so the counts \
      below are short of them: {escapeHtml (String.intercalate ", " failures.toList)}.\
      </p>"
  out := out ++ "\
    <p>Every example of <code>Aeneas/SLPoC/Tests/Examples</code> beside the artifact \
    it ports and, where one exists, beside an <em>unverified</em> Rust implementation \
    of roughly the same data structure.</p>\
    <ul>\
    <li>Comments and blank lines do not count, and neither does a line left under \
    four characters wide once its comments are removed.</li>\
    <li>Delimiters alone do not count: <code>}</code>, <code>);</code>, \
    <code>·</code>.</li>\
    <li>Import, module and scope boilerplate does not count: <code>import</code>, \
    <code>namespace</code>, <code>open</code>, <code>use</code>, <code>mod</code>, \
    <code>Require</code>.</li>\
    <li>A Rust attribute carrying no verification content does not count: \
    <code>#[inline]</code>, <code>#[derive(…)]</code>, <code>#[stable(…)]</code>. \
    <code>#[requires(…)]</code> and <code>#[verifier::…]</code> do.</li>\
    <li>Every line that remains is charged to one of three buckets.</li>\
    </ul>"
  out := out ++ "<p>Which bucket a line lands in is decided by the construct it \
    uses, so each language is read on its own terms.</p>\
    <ul>\
    <li><strong>Lean</strong> — <code>def</code>, <code>structure</code> and \
    <code>inductive</code> are code; a <code>theorem</code> or <code>lemma</code> \
    statement, a <code>def</code> valued in <code>IProp</code> or <code>Prop</code>, \
    and <code>@[…]</code>/<code>attribute</code> are spec; what follows \
    <code>:= by</code>, and <code>termination_by</code>/<code>decreasing_by</code>, \
    are proof.</li>\
    <li><strong>Rust, Verus, Creusot</strong> — <code>exec fn</code>, \
    <code>struct</code> and <code>enum</code> are code; <code>spec fn</code>, \
    <code>#[logic]</code>, the <code>requires</code>/<code>ensures</code>/\
    <code>decreases</code>/<code>invariant</code> clauses and <code>Ghost&lt;…&gt;</code> \
    fields are spec; <code>proof fn</code> bodies, <code>proof { … }</code>, \
    <code>assert</code>/<code>assume</code>/<code>reveal</code>, <code>let ghost</code> \
    and <code>let tracked</code> are proof.</li>\
    <li><strong>F*, Pulse</strong> — <code>fn</code> bodies, <code>let</code> and \
    <code>type</code> are code; <code>requires</code>/<code>ensures</code>/\
    <code>preserves</code>/<code>returns</code>/<code>invariant</code> and \
    <code>slprop</code>-valued definitions are spec; <code>ghost fn</code>, \
    <code>Lemma</code>s and the ghost steps <code>assert</code>/<code>rewrite</code>/\
    <code>fold</code>/<code>unfold</code>/<code>with … .</code> are proof.</li>\
    <li><strong>Rocq, Iris</strong> — a HeapLang program (<code>: expr</code>, \
    <code>: val</code>, <code>λ:</code>) is code; <code>Lemma</code> and \
    <code>Theorem</code> statements, the other <code>Definition</code>s, \
    <code>Notation</code> and <code>Ltac</code> are spec; \
    <code>Proof. … Qed.</code> is proof.</li>\
    <li>The rule is a heuristic, and it is deliberately generous to code: a ratio \
    read off it understates rather than overstates what verification costs.</li>\
    </ul>"
  out := out ++ "<div class='legend'>\
    <span class='key'><i class='seg code' style='width:.85rem'></i> \
    <strong>code</strong></span>\
    <span class='key'><i class='seg spec' style='width:.85rem'></i> \
    <strong>spec</strong></span>\
    <span class='key'><i class='seg proof' style='width:.85rem'></i> \
    <strong>proof</strong></span></div>"
  -- Only a port that answers the whole of its artifact may be divided by it.
  let comparable := examples.filter fun e => e.coverage == "full" && e.source.total > 0
  let fragments := examples.filter fun e => e.coverage == "fragment" && e.source.total > 0
  let comparablePort := comparable.foldl (fun acc e => acc.union e.port) {}
  let comparableSource := comparable.foldl (fun acc e => acc.union e.source) {}
  let compScale := max comparablePort.total comparableSource.total
  out := out ++ s!"<h2>The comparable examples</h2>\
    <p>Adding every example up would compare a kernel against a library: \
    {fragments.size} of the ports deliberately answer part of a larger upstream file \
    — one of them a deliberately downscaled benchmark. Only the {comparable.size} \
    whose port answers its artifact as a whole can be divided by it, and only those \
    are added up here.</p><div class='totals'>"
  let totalRow (label : String) (c : Counts) (tag : String) : String :=
    s!"<span><strong>{label}</strong></span>\
      <span>{bar c compScale}</span><span>{countsCell c} {tag}</span>"
  out := out ++ totalRow "Original artifacts" comparableSource ""
  out := out ++ totalRow "Aeneas+SL" comparablePort
    s!"<span class='ratio' title='the port divided by the artifact above'>\
      {ratio comparablePort.total comparableSource.total}</span>"
  out := out ++ "</div>"
  out := out ++ s!"<p>Over those {comparable.size} examples the port costs \
    {ratio comparablePort.total comparableSource.total} the artifact it answers: \
    {ratio comparablePort.code comparableSource.code} on what runs, and \
    {ratio comparablePort.verification comparableSource.verification} on \
    specification and proof. It spends \
    {percent comparablePort.verification comparablePort.total} of its lines on \
    verification, the artifact \
    {percent comparableSource.verification comparableSource.total}.</p>"
  out := out ++ s!"<p class='dim'>Every file is still counted, and every example \
    below still shows both figures: {ports.size} ports, {sources.size} artifacts over \
    {(examples.filter (·.source.total > 0)).size} examples — several ports answer more \
    than one upstream file, a Pulse module and its interface or the four chapters of \
    the Iris tutorial — and {references.size} unverified Rust references, which being \
    unverified are all <code>code</code>. The {fragments.size} fragmentary examples are \
    marked as such, and sort last by ratio.</p>"
  out := out ++ s!"<h2>Can it be written in safe Rust?</h2>\
    <p>Aeneas translates <em>safe</em> Rust, so each example records whether its \
    program is expressible in that fragment at all — a property of the aliasing the \
    example is about, not of its proof.</p><ul>\
    <li><span class='badge v-yes'>Safe Rust</span> {count "yes"} examples — \
    expressible in safe Rust, at worst by replacing a raw pointer with an index, a \
    <code>Box</code>, or a <code>&amp;mut</code>.</li>\
    <li><span class='badge v-no'>Unsafe Rust</span> {count "no"} — the aliasing \
    <em>is</em> the point: intrusive links, a doubly-linked list, a free list threaded \
    through freed memory, hardware page tables.</li>\
    <li><span class='badge v-na'>N/A</span> {count "n/a"} — no single answer applies: \
    the file holds no program at all, or part of it is safe and the rest needs \
    <code>unsafe</code>, a borrow checker that does not exist yet, or has no \
    sequential Rust counterpart.</li></ul>"
  out := out ++ "<h2>Examples</h2><div class='controls'>\
    <label>Bars <select id='scale'>\
    <option value='absolute'>to a common scale</option>\
    <option value='relative'>as proportions</option></select></label>\
    <label>Sort by <select id='sort'>\
    <option value='name'>name</option>\
    <option value='port'>size of the port</option>\
    <option value='proof'>share of specification and proof</option>\
    <option value='source'>size of the artifact</option>\
    <option value='ratio'>port ÷ artifact</option></select></label>\
    <fieldset><span>Show</span>\
    <label><input type='checkbox' name='verdict' value='yes' checked> Safe Rust</label>\
    <label><input type='checkbox' name='verdict' value='no' checked> Unsafe Rust</label>\
    <label><input type='checkbox' name='verdict' value='na' checked> N/A</label>\
    </fieldset><button type='button' id='expand'>Expand all</button></div>"
  out := out ++ "<p>Each example carries three bars, one per line, all drawn to a \
    scale common to the whole section, so their lengths may be compared down the \
    page as well as within an example:</p><ul>\
    <li><strong>artifact</strong> — the upstream file the port answers, in Verus, \
    Pulse, Creusot or Rocq;</li>\
    <li><strong>Aeneas+SL</strong> — this port, with the ratio between the two \
    where it answers the whole of that file;</li>\
    <li><strong>Rust</strong> — an unverified Rust implementation of roughly the \
    same structure, which having no proof is one colour only.</li></ul>\
    <p>A bar is divided into the three buckets, and hovering a segment gives its \
    count:</p>\
    <div class='legend'>\
    <span class='key'><i class='seg code' style='width:.85rem'></i> \
    <strong>code</strong></span>\
    <span class='key'><i class='seg spec' style='width:.85rem'></i> \
    <strong>spec</strong></span>\
    <span class='key'><i class='seg proof' style='width:.85rem'></i> \
    <strong>proof</strong></span>\
    <span class='key'><span class='bar empty' style='width:3rem'></span> \
    not counted</span></div>\
    <p class='dim'>The figure beside each bar is its total, then \
    <code>(code + spec + proof)</code>. Open a row for the verdicts, the files, and \
    every declaration.</p>\
    <div id='examples'>"
  for e in examples do
    out := out ++ renderExample e scale
  out := out ++ "</div>"
  out := out ++ renderHotspots files
  out := out ++ s!"<h2>Provenance</h2><p>Generated by \
    <code>Aeneas/SLPoC/Tests/Examples/scripts/SourceLoc.lean</code> from \
    <code>{escapeHtml manifest}</code>, which pins every source to a commit and to \
    its SHA-256. The numbers are also written, per file and per declaration, to \
    <code>source-loc.json</code>.</p>"
  return out ++ s!"<script>{script}</script></body></html>\n"

/-! ## Entry point -/

structure Options where
  manifest : System.FilePath := "Aeneas/SLPoC/Tests/Examples/reports/sources-manifest.json"
  examples : System.FilePath := "Aeneas/SLPoC/Tests/Examples"
  out : System.FilePath := "Aeneas/SLPoC/Tests/Examples/reports/source-loc.json"
  html : System.FilePath := "Aeneas/SLPoC/Tests/Examples/reports/source-loc.html"
  cache : System.FilePath := ".lake/source-loc-cache"
  offline : Bool := false

def usage : String :=
  "usage: lake env lean --run Aeneas/SLPoC/Tests/Examples/scripts/SourceLoc.lean \
    [-o OUT.json] [--html OUT.html] [--manifest FILE] [--examples DIR] \
    [--cache DIR] [--offline]"

partial def parseArgs (args : List String) (opts : Options := {}) : Except String Options :=
  match args with
  | [] => .ok opts
  | "-o" :: out :: rest | "--out" :: out :: rest => parseArgs rest { opts with out }
  | "--html" :: html :: rest => parseArgs rest { opts with html }
  | "--manifest" :: manifest :: rest => parseArgs rest { opts with manifest }
  | "--examples" :: examples :: rest => parseArgs rest { opts with examples }
  | "--cache" :: cache :: rest => parseArgs rest { opts with cache }
  | "--offline" :: rest => parseArgs rest { opts with offline := true }
  | arg :: _ => .error s!"unknown argument `{arg}`\n{usage}"

def main (args : List String) : IO UInt32 := do
  let opts ← match parseArgs args with
    | .ok opts => pure opts
    | .error msg => IO.eprintln msg; return 1
  let manifestText ← IO.FS.readFile opts.manifest
  let manifestJson ← IO.ofExcept (Json.parse manifestText)
  let entries ← IO.ofExcept (parseManifest manifestJson)
  IO.FS.createDirAll opts.cache
  let mut files : Array FileReport := #[]
  let mut mismatches : Array String := #[]
  -- Files the manifest names but this run could not read: without them the counts
  -- are silently short, so they belong in the report and not only on stderr.
  let mut failures : Array String := #[]
  for entry in entries do
    -- The port.
    let leanPath := opts.examples / entry.lean
    if ← leanPath.pathExists then
      let text ← IO.FS.readFile leanPath
      let (physical, counts, loose, decls) := countFile .lean text
      files := files.push
        { role := "port", example_ := entry.lean, path := leanPath.toString
          url := none, downloadUrl := none, language := .lean
          physicalLines := physical, counts
          looseCounts := loose, sha256 := none, sha256Expected := none
          safe := none, note := none, decls }
    else
      IO.eprintln s!"warning: {leanPath} does not exist"
    -- The artifacts it ports, then the unverified Rust implementations of the
    -- same data structure.
    for (role, srcs) in [("source", entry.sources), ("reference", entry.references)] do
      for src in srcs do
        unless src.downloadable do
          IO.println s!"skipping {src.url}: {src.reason.getD "not downloadable"}"
          continue
        let some path ← fetch opts.cache src.url opts.offline
          | failures := failures.push s!"{entry.lean}: {src.url}"
            continue
        let text ← IO.FS.readFile path
        let digest ← sha256Of path
        if let (some a, some b) := (digest, src.sha256) then
          if a != b then
            mismatches := mismatches.push s!"{src.url}: expected {b}, got {a}"
        let (physical, counts, loose, decls) := countFile src.language text
        files := files.push
          { role, example_ := entry.lean, path := src.path
            url := some src.viewUrl
            downloadUrl := if src.viewUrl == src.url then none else some src.url
            language := src.language, physicalLines := physical
            counts, looseCounts := loose, sha256 := digest, sha256Expected := src.sha256
            safe := src.safe, note := src.note, decls }
  -- Per-example comparison.
  let mut examples : Array ExampleReport := #[]
  let mut comparisons : Array Json := #[]
  for entry in entries do
    let ofRole (role : String) := files.filter fun f => f.example_ == entry.lean && f.role == role
    let port := ofRole "port"
    let source := ofRole "source"
    let reference := ofRole "reference"
    let (verdict, reason) := entry.safeRust.getD ("n/a", "")
    let (coverage, coverageNote) := entry.coverage.getD ("n/a", "")
    examples := examples.push
      { name := entry.lean, project := entry.project, note := entry.note
        verdict, reason, coverage, coverageNote
        port := sumCounts port, source := sumCounts source
        reference := sumCounts reference
        files := files.filter (·.example_ == entry.lean) }
    comparisons := comparisons.push <| Json.mkObj
      [ ("example", Json.str entry.lean), ("project", Json.str entry.project),
        ("note", optJson entry.note),
        ("safeRust",
          match entry.safeRust with
          | none => Json.null
          | some (verdict, reason) =>
            Json.mkObj [("verdict", Json.str verdict), ("reason", Json.str reason)]),
        ("coverage",
          match entry.coverage with
          | none => Json.null
          | some (verdict, note) =>
            Json.mkObj [("verdict", Json.str verdict), ("note", Json.str note)]),
        ("port", countsJson (sumCounts port)),
        ("source", countsJson (sumCounts source)),
        ("reference", countsJson (sumCounts reference)),
        -- Only a port that answers the whole of its artifact may be divided by it.
        ("ratio",
          if entry.coverage.any (·.1 == "full") && (sumCounts source).total > 0 then
            Json.str (ratio (sumCounts port).total (sumCounts source).total)
          else Json.null),
        ("sourceFiles", Json.arr (source.map fun f => Json.str (f.url.getD f.path))),
        ("referenceFiles", Json.arr (reference.map fun f => Json.str (f.url.getD f.path))),
        ("sourcesCounted", toJson source.size),
        ("sourcesNotCounted",
          toJson (entry.sources.filter (!·.downloadable) |>.size)) ]
  let ports := files.filter (·.role == "port")
  let sources := files.filter (·.role == "source")
  let references := files.filter (·.role == "reference")
  let report := Json.mkObj
    [ ("generatedBy", Json.str "Aeneas/SLPoC/Tests/Examples/scripts/SourceLoc.lean")
    , ("manifest", Json.str opts.manifest.toString)
    , ("countingRules", Json.mkObj
        [ ("relevantLine", Json.str
            "at least 4 characters after comment removal, not delimiters only, not \
             import/module/scope boilerplate")
        , ("uncountedAttribute", Json.str
            "a Rust attribute with no verification content (`#[inline]`, \
             `#[derive(…)]`, `#[stable(…)]`) is metadata, and is not counted")
        , ("code", Json.str "computational content executed at run time")
        , ("spec", Json.str
            "specifications and annotations: pre/postconditions, invariants, \
             representation predicates, theorem statements, ghost state, attributes")
        , ("proof", Json.str
            "proof material: tactic scripts, proof blocks, asserts, ghost steps") ])
    , ("totals", Json.mkObj
        [ ("ports", countsJson (sumCounts ports))
        , ("sources", countsJson (sumCounts sources))
        , ("references", countsJson (sumCounts references))
        , ("portFiles", toJson ports.size)
        , ("sourceFiles", toJson sources.size)
        , ("referenceFiles", toJson references.size)
        , ("safeRust", Json.mkObj (["yes", "no", "n/a"].map fun verdict =>
            (verdict, toJson (entries.filter
              (fun e => e.safeRust.any (·.1 == verdict)) |>.size))))
        , ("declarations", toJson (files.foldl (· + ·.decls.size) 0)) ])
    , ("checksumMismatches", Json.arr (mismatches.map Json.str))
    , ("downloadFailures", Json.arr (failures.map Json.str))
    , ("complete", Json.bool (failures.isEmpty && mismatches.isEmpty))
    , ("comparisons", Json.arr comparisons)
    , ("files", Json.arr (files.map fileJson)) ]
  IO.FS.createDirAll (opts.out.parent.getD ".")
  IO.FS.writeFile opts.out (report.pretty ++ "\n")
  IO.FS.createDirAll (opts.html.parent.getD ".")
  IO.FS.writeFile opts.html
    (renderHtml examples files opts.manifest.toString failures)
  for m in mismatches do
    IO.eprintln s!"warning: checksum mismatch for {m}"
  for f in failures do
    IO.eprintln s!"warning: could not count {f}; the totals are short of it"
  let p := sumCounts ports
  let s := sumCounts sources
  IO.println s!"ports:   {p.total} relevant lines ({p.code} code, {p.spec} spec, \
    {p.proof} proof) over {ports.size} files"
  IO.println s!"sources: {s.total} relevant lines ({s.code} code, {s.spec} spec, \
    {s.proof} proof) over {sources.size} files"
  let r := sumCounts references
  IO.println s!"refs:    {r.total} relevant lines ({r.code} code, {r.spec} spec, \
    {r.proof} proof) over {references.size} files"
  IO.println s!"wrote {opts.out} and {opts.html}"
  return 0

end Aeneas.SepLogic.SourceLoc

def main (args : List String) : IO UInt32 := Aeneas.SepLogic.SourceLoc.main args
