(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [demo]: type definitions *)
module Demo.Types
open Primitives

#set-options "--z3rlimit 50 --fuel 1 --ifuel 1"

(** [demo::opaque::S] *)
val opaque_s_t : Type0

