-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hashmap]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas.Std
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- The state type used in the state-error monad -/
axiom State : Type

