import Aeneas.Tactic.SepLogic.Init
import Lean.Meta.Tactic.AC

/-!
# `iframe` and `isimp`

The entailment solver of the separation-logic proof mode: the `IFrame` engine
that cancels the assertions of a goal up to associativity/commutativity, and the
two tactics built directly on it.
-/

namespace Aeneas.SepLogic

open Lean Lean.Elab Lean.Meta Lean.Elab.Tactic

/-! ## The `isimpl` engine

See the `isimpl` documentation below for the phases it goes through. -/

namespace IFrame

private def isConnective (e : Expr) : Bool :=
  let head := e.consumeMData.getAppFn
  head.isConstOf ``sep || head.isConstOf ``ipure ||
    head.isConstOf ``iexists || head.isConstOf `Aeneas.SepLogic.emp ||
    -- `wand` is *defined* as an existential; unfolding it would be a disaster.
    head.isConstOf ``wand || head.isConstOf ``postWand || head.isConstOf ``iforall

/-- Is `e` a magic wand?  Returns whether it is a postcondition wand. -/
private def wand? (e : Expr) : Option Bool :=
  let e := e.consumeMData
  if e.isAppOfArity ``postWand 3 then some true
  else if e.isAppOfArity ``wand 2 then some false
  else none

/-- Expose the head connective (`sep`, `ipure`, `iexists` or `emp`) of a
separation-logic assertion, by unfolding a definition that is a mere wrapper
around one — `wellFormed s l` is `⌜…⌝ ∗ nodes l`, `isList s vs` is `∃ l, …`.

Exactly one unfolding is performed, and only when it does reveal a connective.
Representation predicates that *compute*, such as `nodes`, are deliberately left
alone: decomposing them is the job of the `iris_simps` lemmas, which would
otherwise never get a chance to fire.  Returns `none` when no connective can be
reached, so that callers keep the original assertion. -/
def exposeConnective? (e : Expr) : MetaM (Option Expr) := do
  let e := (← instantiateMVars e).consumeMData
  if isConnective e then return some e
  match ← unfoldDefinition? e with
  | some e' => if isConnective e' then return some e' else return none
  | none => return none

@[inherit_doc exposeConnective?]
def exposeConnective (e : Expr) : MetaM Expr :=
  return (← exposeConnective? e).getD e

private def reducePostApplication (e : Expr) : MetaM Expr := do
  let e ← instantiateMVars e
  let e ← Lean.Core.betaReduce e
  let (fn, args) := e.consumeMData.withApp fun fn args => (fn, args)
  if fn.isConstOf ``postSep && args.size = 4 then
    return mkApp2 (mkConst ``sep) (mkApp args[1]! args[3]!) args[2]!
  return e

partial def flatten (e : Expr) : MetaM (Array Expr) := do
  let e ← reducePostApplication e
  let (fn, args) := e.consumeMData.withApp fun fn args => (fn, args)
  if fn.isConstOf ``sep && args.size = 2 then
    return (← flatten args[0]!) ++ (← flatten args[1]!)
  if fn.isConstOf `Aeneas.SepLogic.emp then
    return #[]
  return #[e]

def mkStar (atoms : Array Expr) : Expr :=
  match atoms.back? with
  | none => mkConst `Aeneas.SepLogic.emp
  | some last =>
    atoms.pop.foldr (init := last) fun atom rest =>
      mkApp2 (mkConst ``sep) atom rest

def removeMatches (available required : Array Expr) :
    MetaM (Option (Array Expr)) := do
  let mut remaining := available
  for expected in required do
    let mut found := none
    for h : i in [:remaining.size] do
      if ← isDefEq expected remaining[i] then
        found := some i
        break
    let some i := found | return none
    remaining :=
      remaining.extract 0 i ++ remaining.extract (i + 1) remaining.size
  return some remaining

/-- Prove `lhs = rhs` when the two sides are the same separating conjunction up
to associativity, commutativity and the `emp` unit. -/
def proveEqAC (lhs rhs : Expr) : TacticM Expr := do
  let eqType ← mkEq lhs rhs
  let proof ← mkFreshExprSyntheticOpaqueMVar eqType
  let .mvar proofId := proof.consumeMData
    | throwError "failed to create an equality proof goal"
  /- `ac_rfl` normalizes modulo associativity and commutativity but does not
     insert or erase the unit, so strip the `emp`s first when it fails. -/
  let tactic ← `(tactic|
    first
      | rfl
      | ac_rfl
      | (simp only [sep_emp_l_eq, sep_emp_r_eq] <;>
          first | rfl | ac_rfl))
  let (goals, _) ← runTactic proofId tactic
  unless goals.isEmpty do
    throwError "could not prove {eqType}"
  return proof

/-- Discharge a pure side-goal generated by the right-hand side of an
entailment.  This runs last, so the goal mentions no leftover metavariable
coming from a right-hand-side existential.

`grind` alone is not enough: the propositions typically mention the projections
of a representation predicate (`headPtr []`, `lastPtr [c]`, …), which only the
simp set computes.  `discharger` overrides the default chain; a `sym => …`
script driving a `register_sym_simp` variant is a good deterministic
alternative to the backtracking `first` below. -/
private def provePure (discharger : Option Syntax.Tactic) (proposition : Expr) :
    TacticM Expr := do
  let proof ← mkFreshExprSyntheticOpaqueMVar proposition
  let .mvar proofId := proof.consumeMData
    | throwError "failed to create a pure proof goal"
  let tactic ←
    match discharger with
    | some tactic => pure tactic
    | none =>
      `(tactic|
        first
          | grind
          | (simp only [iris_simps, *]; done)
          | (simp only [iris_simps, *]; grind)
          | (simp_all; done)
          | (simp_all; grind))
  let (goals, _) ← runTactic proofId tactic
  unless goals.isEmpty do
    throwError "could not prove pure assertion {proposition}"
  return proof

/-- Is `destination` a frame-inference destination, i.e. of the shape
`Hcallee ∗ ?F` for an unassigned metavariable `?F`?

In that mode neither side of the entailment may be reorganized: anything we
extracted from the left-hand side would be lost from the frame `?F`, and could
not even be mentioned by it, since `?F` was created in an outer context. This
is exactly the limitation that the ramified frame rule works around.

`Hcallee` may itself be an existential, in which case floating that existential
out would turn the destination into `∃ x, Hcallee' x ∗ ?F` and hide the frame:
the decision must therefore be taken *before* any normalization. -/
private def frameMVar? (destination : Expr) : MetaM (Option MVarId) := do
  let (destFn, destArgs) :=
    destination.consumeMData.withApp fun fn args => (fn, args)
  unless destFn.isConstOf ``sep && destArgs.size = 2 do return none
  match (← instantiateMVars destArgs[1]!).consumeMData with
  | .mvar mvarId => if ← mvarId.isAssigned then pure none else pure (some mvarId)
  | _ => pure none

/-- Is the goal a frame-inference goal?  See `frameMVar?`. -/
private def isFrameInference (goal : MVarId) : MetaM Bool := goal.withContext do
  let target ← instantiateMVars (← goal.getType)
  let (fn, args) := target.consumeMData.withApp fun fn args => (fn, args)
  unless fn.isConstOf ``Entails && args.size = 2 do return false
  return (← frameMVar? (← reducePostApplication args[1]!)).isSome

private def simpEntailment (goal : MVarId) (simpOnly : Bool)
    (args : Aeneas.Simp.SimpArgs) : TacticM MVarId := do
  /- Restore the goals we are not working on: `Simp.simpAt` acts on the main
     goal, and dropping the others would silently remove them from the state. -/
  let saved ← getGoals
  try
    setGoals [goal]
    let _ ← Aeneas.Simp.simpAt simpOnly
      { dsimp := false, failIfUnchanged := false, maxDischargeDepth := 1 }
      args (.targets #[] true)
    match ← getGoals with
    | [] => throwError "the entailment was unexpectedly closed while normalizing it"
    | goal :: _ => pure goal
  finally
    setGoals saved

/-- Float the existentials of a separating conjunction to its head, where
`pullLeft` and `instantiateRightExists` can see them.  Only used outside of
frame-inference mode: it can hide the frame metavariable behind an existential
(see `frameMVar?`). -/
private def floatExists (goal : MVarId) : TacticM MVarId :=
  simpEntailment goal true
    { addSimpThms :=
        -- Erase the `emp`s first, so that they do not get pushed under a binder.
        #[``sep_emp_l_eq, ``sep_emp_r_eq,
          ``sep_exists_l_eq, ``sep_exists_r_eq] }

/-- Decompose the representation predicates of an entailment into the cells they
own, using the `iris_simps` set.  Unlike `floatExists` this is not always
desirable, so `iframe` only resorts to it when the plain cancellation fails. -/
private def decompose (goal : MVarId) : TacticM MVarId := do
  simpEntailment goal false { simpThms := #[← irisSimpExt.getTheorems] }

/-- Rewrite an assertion into an equivalent one whose connectives are all
visible, by unfolding definitions such as `wellFormed` or `isList` through the
separating conjunctions.  Only delta/beta reduction is involved, so the result is
definitionally equal to the input. -/
private partial def exposeAll (e : Expr) : MetaM Expr := do
  let e ← reducePostApplication e
  let e := (← exposeConnective? e).getD e
  let (fn, args) := e.consumeMData.withApp fun fn args => (fn, args)
  if fn.isConstOf ``sep && args.size = 2 then
    return mkApp2 (mkConst ``sep) (← exposeAll args[0]!) (← exposeAll args[1]!)
  return e

/-- Put the entailment of `goal` in the exposed form computed by `exposeAll`. -/
private def exposeGoal (goal : MVarId) : TacticM MVarId := goal.withContext do
  let target ← instantiateMVars (← goal.getType)
  let (fn, args) := target.consumeMData.withApp fun fn args => (fn, args)
  unless fn.isConstOf ``Entails && args.size = 2 do return goal
  let exposed ← mkAppM ``Entails #[← exposeAll args[0]!, ← exposeAll args[1]!]
  if exposed == target then return goal
  try goal.change exposed catch _ => pure goal

/-- Introduce the existentials of the left-hand side and move its pure facts
into the local context. Returns the residual goal. -/
private partial def pullLeft (goal : MVarId) : TacticM MVarId := do
  /- In frame-inference mode the left-hand side must be preserved verbatim.  The
     decision has to be taken *before* `floatExists`, which could otherwise turn
     `Hcallee ∗ ?F` into `∃ x, Hcallee' x ∗ ?F` and hide the frame. -/
  if ← isFrameInference goal then return goal
  /- Re-expose and re-float at every step: extracting a pure fact or a quantifier
     may reveal a definition (`isList`, …) hiding the next one. -/
  let goal ← floatExists (← exposeGoal goal)
  if ← isFrameInference goal then return goal
  goal.withContext do
  let target ← instantiateMVars (← goal.getType)
  let (fn, args) := target.consumeMData.withApp fun fn args => (fn, args)
  unless fn.isConstOf ``Entails && args.size = 2 do return goal
  let source ← reducePostApplication args[0]!
  let destination ← reducePostApplication args[1]!
  let (sourceFn, sourceArgs) :=
    source.consumeMData.withApp fun fn args => (fn, args)
  if sourceFn.isConstOf ``iexists && sourceArgs.size = 2 then
    let some u := sourceFn.constLevels!.head?
      | throwError "could not determine the universe of {source}"
    let ι := sourceArgs[0]!
    let J := sourceArgs[1]!
    let newType ← withLocalDeclD `x ι fun x => do
      mkForallFVars #[x] (← mkAppM ``Entails #[← Core.betaReduce (mkApp J x), destination])
    let newGoal ← mkFreshExprSyntheticOpaqueMVar newType
    goal.assign (mkAppN (mkConst ``entails_exists_l [u]) #[ι, destination, J, newGoal])
    let (_, next) ← newGoal.mvarId!.intro1P
    return ← pullLeft next
  let atoms ← flatten source
  let some i := atoms.findIdx? fun atom =>
      atom.consumeMData.isAppOfArity ``ipure 1
    | return goal
  let atom := atoms[i]!
  let proposition := atom.consumeMData.appArg!
  let rest := mkStar (atoms.eraseIdx! i)
  let newType ← withLocalDeclD `h proposition fun h => do
    mkForallFVars #[h] (← mkAppM ``Entails #[rest, destination])
  let newGoal ← mkFreshExprSyntheticOpaqueMVar newType
  let extract := mkAppN (mkConst ``entails_pure_l)
    #[proposition, rest, destination, newGoal]
  let reordered := mkApp2 (mkConst ``sep) atom rest
  let reorder ← mkAppM ``entails_of_eq #[← proveEqAC source reordered]
  goal.assign (← mkAppM ``entails_trans #[reorder, extract])
  let (_, next) ← newGoal.mvarId!.intro1P
  pullLeft next

/-- Replace a right-hand-side `∃ x, J x` by `J ?x` for a fresh metavariable
`?x`, to be determined by the cancellation phase. -/
private partial def instantiateRightExists (goal : MVarId) : TacticM MVarId := do
  if ← isFrameInference goal then return goal
  let goal ← floatExists (← exposeGoal goal)
  if ← isFrameInference goal then return goal
  goal.withContext do
  let target ← instantiateMVars (← goal.getType)
  let (fn, args) := target.consumeMData.withApp fun fn args => (fn, args)
  unless fn.isConstOf ``Entails && args.size = 2 do return goal
  let source := args[0]!
  let destination ← reducePostApplication args[1]!
  let (destFn, destArgs) :=
    destination.consumeMData.withApp fun fn args => (fn, args)
  unless destFn.isConstOf ``iexists && destArgs.size = 2 do return goal
  let some u := destFn.constLevels!.head?
    | throwError "could not determine the universe of {destination}"
  let ι := destArgs[0]!
  let J := destArgs[1]!
  let witness ← mkFreshExprMVar ι
  let newType ← mkAppM ``Entails #[source, ← Core.betaReduce (mkApp J witness)]
  let newGoal ← mkFreshExprSyntheticOpaqueMVar newType
  goal.assign (mkAppN (mkConst ``entails_exists_r [u]) #[ι, source, J, witness, newGoal])
  instantiateRightExists newGoal.mvarId!

/-- Replace the top-level existentials of the callee precondition of a
frame-inference goal by metavariables, so that the cancellation can pick the
witnesses.  Returns the peeled assertion together with a proof that it entails
the original one.

Unlike `pullLeft`, this is sound in frame-inference mode: it introduces
metavariables, not free variables, so nothing can escape the scope of the frame
metavariable. -/
private partial def peelRequiredExists (required : Expr) :
    MetaM (Expr × Expr × Array MVarId) := do
  let required ← reducePostApplication required
  let (fn, args) := required.consumeMData.withApp fun fn args => (fn, args)
  unless fn.isConstOf ``iexists && args.size = 2 do
    return (required, ← mkAppM ``entails_refl #[required], #[])
  let some u := fn.constLevels!.head?
    | throwError "could not determine the universe of {required}"
  let ι := args[0]!
  let J := args[1]!
  let witness ← mkFreshExprMVar ι
  let body ← Core.betaReduce (mkApp J witness)
  let (peeled, peeledEntailsBody, witnesses) ← peelRequiredExists body
  let bodyEntailsRequired := mkAppN (mkConst ``entails_exists_r [u])
    #[ι, body, J, witness, ← mkAppM ``entails_refl #[body]]
  return (peeled,
    ← mkAppM ``entails_trans #[peeledEntailsBody, bodyEntailsRequired],
    witnesses.push witness.mvarId!)

mutual

/-- Prove `residual ⊢ wand` by the introduction rule of the wand, and hand the
resulting entailment back to `solveGoal`. -/
partial def proveWand (discharger : Option Syntax.Tactic)
    (residual wand : Expr) : TacticM Expr := do
  let some isPostcondition := wand? wand
    | throwError "expected a magic wand, got {wand}"
  let args := wand.consumeMData.getAppArgs
  let (lemmaName, premise) ←
    if isPostcondition then
      pure (``postWand_intro,
        ← mkAppM ``postEntails #[← mkAppM ``postSep #[args[1]!, residual], args[2]!])
    else
      pure (``wand_intro,
        ← mkAppM ``Entails #[mkApp2 (mkConst ``sep) args[0]! residual, args[1]!])
  let premiseGoal ← mkFreshExprSyntheticOpaqueMVar premise
  solveGoal discharger premiseGoal.mvarId!
  mkAppM lemmaName #[premiseGoal]

partial def solveHimpl (discharger : Option Syntax.Tactic) (goal : MVarId) :
    TacticM Unit := goal.withContext do
  let target ← instantiateMVars (← goal.getType)
  let (fn, args) := target.consumeMData.withApp fun fn args => (fn, args)
  unless fn.isConstOf ``Entails && args.size = 2 do
    throwError "expected a separation-logic entailment"
  let source ← reducePostApplication args[0]!
  let destination ← reducePostApplication args[1]!
  let sourceAtoms ← flatten source

  if let some frameMVar := ← frameMVar? destination then
    let destArgs := destination.consumeMData.getAppArgs
    let original ← reducePostApplication destArgs[0]!
    /- Cancel `required` against the source and put the leftovers in the frame.
       `weakening` proves `required ⊢ original`, and `witnesses` are the
       metavariables `peelRequiredExists` introduced: the cancellation has to
       determine all of them, otherwise the proof term would be incomplete. -/
    let solveWith (required weakening : Expr) (witnesses : Array MVarId) :
        TacticM Bool := do
      let requiredAtoms ← flatten required
      let some frameAtoms ← removeMatches sourceAtoms requiredAtoms
        | return false
      for witness in witnesses do
        unless ← witness.isAssigned do return false
      let frame := mkStar frameAtoms
      frameMVar.assign frame
      let cancelled := mkApp2 (mkConst ``sep) (← instantiateMVars required) frame
      let reorder ← mkAppM ``entails_of_eq #[← proveEqAC source cancelled]
      let weaken ← mkAppM ``sep_mono
        #[← instantiateMVars weakening, ← mkAppM ``entails_refl #[frame]]
      goal.assign (← mkAppM ``entails_trans #[reorder, weaken])
      return true
    let state ← saveState
    /- First try the callee precondition as it stands: it may well be owned as a
       single opaque assertion (an `isList`, say) by the caller.  Only if that
       fails do we open its existentials. -/
    unless ← solveWith original (← mkAppM ``entails_refl #[original]) #[] do
      state.restore
      let (peeled, weakening, witnesses) ← peelRequiredExists original
      unless ← solveWith peeled weakening witnesses do
        state.restore
        throwError "required spatial assertions are not present in the precondition\
          \nsource: {source}\ndestination: {destination}"
  else
    let destinationAtoms ← flatten destination
    let mut remaining := sourceAtoms
    let mut matched : Array Expr := #[]
    /- Cancellation phase.  A destination atom that cannot be cancelled must be
       pure — we record it and discharge it below, once every metavariable
       introduced for a right-hand-side existential has had a chance to be
       instantiated by unification — or a magic wand, which then absorbs
       everything the cancellation leaves over.  That is what the ramified frame
       rule puts on the right in place of a frame metavariable; there can be only
       one of them. -/
    let mut deferredPure : Array Expr := #[]
    let mut absorbing : Option Expr := none
    for expected in destinationAtoms do
      let mut found := none
      for h : i in [:remaining.size] do
        if ← isDefEq expected remaining[i] then
          found := some i
          break
      if let some i := found then
        matched := matched.push expected
        remaining :=
          remaining.extract 0 i ++ remaining.extract (i + 1) remaining.size
      else if expected.consumeMData.isAppOfArity ``ipure 1 then
        deferredPure := deferredPure.push expected
      else if (wand? expected).isSome then
        /- Note that we get here only when the wand could *not* be cancelled
           against an identical one on the left. -/
        if absorbing.isSome then
          throwError "cannot handle more than one magic wand on the right-hand \
            side\ndestination: {destination}"
        absorbing := some expected
      else
        throwError "required spatial assertions are not present\
          \nsource: {source}\ndestination: {destination}\nmissing: {expected}"
    let mut generatedPure : Array (Expr × Expr) := #[]
    for expected in deferredPure do
      let proposition ← instantiateMVars expected.consumeMData.appArg!
      generatedPure := generatedPure.push (expected, ← provePure discharger proposition)
    let matchedAssertion := mkStar matched
    /- `sourceToMatched : source ⊢ matchedAssertion ∗ absorbed`, where `absorbed`
       is the wand if there is one (which then swallows the residual resources),
       and `emp` otherwise (the residual resources must then be discardable). -/
    let (matchedAssertion, sourceToMatched) ←
      match absorbing with
      | some absorbingAtom =>
        let residual := mkStar remaining
        let reordered := mkApp2 (mkConst ``sep) matchedAssertion residual
        let reorderProof ← mkAppM ``entails_of_eq #[← proveEqAC source reordered]
        let residualToAbsorber ← proveWand discharger residual absorbingAtom
        let absorbProof ← mkAppM ``sep_mono
          #[← mkAppM ``entails_refl #[matchedAssertion], residualToAbsorber]
        pure (mkApp2 (mkConst ``sep) matchedAssertion absorbingAtom,
          ← mkAppM ``entails_trans #[reorderProof, absorbProof])
      | none =>
        let discardedAtoms := remaining
        let proof ←
          if discardedAtoms.isEmpty then
            mkAppM ``entails_of_eq #[← proveEqAC source matchedAssertion]
          else
            let discarded := mkStar discardedAtoms
            let reordered := mkApp2 (mkConst ``sep) matchedAssertion discarded
            let reorderProof ← mkAppM ``entails_of_eq #[← proveEqAC source reordered]
            /- The logic is affine, so whatever the cancellation leaves over is
               discardable. -/
            let eliminateProof ← mkAppM ``sep_elim_right
              #[matchedAssertion, discarded]
            mkAppM ``entails_trans #[reorderProof, eliminateProof]
        pure (matchedAssertion, proof)
    let mut current := matchedAssertion
    let mut insertionProof ← mkAppM ``entails_refl #[current]
    for (pureAtom, pureProof) in generatedPure do
      let insertProof ← mkAppM ``pure_sep_intro #[current, pureProof]
      insertionProof ← mkAppM ``entails_trans #[insertionProof, insertProof]
      current := mkApp2 (mkConst ``sep) pureAtom current
    let destination ← instantiateMVars destination
    let eqProof ← proveEqAC current destination
    let reorderProof ← mkAppM ``entails_of_eq #[eqProof]
    let matchedToDestination ← mkAppM ``entails_trans #[insertionProof, reorderProof]
    goal.assign (← mkAppM ``entails_trans #[sourceToMatched, matchedToDestination])

partial def solveGoal (discharger : Option Syntax.Tactic) (goal : MVarId) :
    TacticM Unit := do
  let target ← instantiateMVars (← goal.getType)
  let (fn, args) := target.consumeMData.withApp fun fn args => (fn, args)
  if fn.isConstOf ``postEntails && args.size = 3 then
    let (_, nextGoal) ← goal.intro1P
    solveGoal discharger nextGoal
  else
    /- Two passes.  The first one only reorganizes the connectives; it is the one
       that succeeds when the assertion to produce is a representation predicate
       applied to a metavariable, which no rewriting could ever match.  The
       second one additionally decomposes the representation predicates with the
       `iris_simps` set, which is what is needed when the two sides of the
       entailment own the same cells but describe them differently. -/
    let pass (decomposing : Bool) : TacticM Unit := do
      let goal ← if decomposing then decompose goal else pure goal
      /- Decide here whether we are inferring a frame: `floatExists` below can
         turn `Hcallee ∗ ?F` into `∃ x, Hcallee' x ∗ ?F` and hide `?F`. -/
      if ← isFrameInference goal then
        /- Expose before decomposing again: `iris_simps` has no lemma for the
           representation predicates themselves (`wellFormed`, `isList`, …), so
           decomposing a folded assertion is a no-op. -/
        let goal ← exposeGoal goal
        let goal ← if decomposing then exposeGoal (← decompose goal) else pure goal
        solveHimpl discharger goal
      else
        let goal ← pullLeft goal
        let goal ← instantiateRightExists goal
        let goal ← exposeGoal goal
        let goal ← if decomposing then exposeGoal (← decompose goal) else pure goal
        solveHimpl discharger goal
    let state ← saveState
    try pass false
    catch firstError =>
      state.restore
      try pass true
      catch secondError =>
        throwError "iframe failed.\n\
          {firstError.toMessageData}\n\
          and, after decomposing the assertions with `iris_simps`:\n\
          {secondError.toMessageData}"

/-- Pull quantifiers and pure facts from an entailment's left-hand side. -/
partial def pullGoal (goal : MVarId) : TacticM MVarId := do
  if ← isFrameInference goal then
    throwError "iintro_entail: this is a frame-inference goal.  Extracting anything \
      from its left-hand side would lose it from the frame, which was created in \
      an outer context; pull at the level of the specification instead, with `iintro`."
  let target ← instantiateMVars (← goal.getType)
  if target.consumeMData.isAppOfArity ``postEntails 3 then
    let (_, next) ← goal.intro1P
    pullLeft next
  else
    pullLeft goal

end

end IFrame

/-- Prove a separation-logic entailment `H₁ ⊢ H₂` (or a postcondition entailment
`Q₁ ⊢+ Q₂`):

1. the existentials of the left-hand side are introduced and its pure facts are
   moved into the local context;
2. the existentials of the right-hand side are replaced by metavariables;
3. the spatial assertions of the right-hand side are cancelled against those of
   the left-hand side, up to associativity/commutativity, which is what
   instantiates the metavariables of step 2;
4. the pure assertions left over on the right-hand side are discharged last —
   after step 3, so that they mention no leftover metavariable.

Unmatched pure assertions of the left-hand side may be discarded; unmatched
spatial assertions are reported as an error.

When the right-hand side is of the shape `H ∗ ?F` for an unassigned
metavariable `?F` (frame inference, as generated by `step`), steps 1 and 2 are
skipped: the residual resources have to end up in the frame rather than in the
local context.

`iframe by tac` uses `tac` instead of the default chain to discharge the pure
side-goals of step 4.  Lean's `sym => …` symbolic-simulation mode is a good
choice when the default chain is too slow or too unpredictable, since it makes
the normalization explicit instead of relying on backtracking:

```
register_sym_simp slPure where
  post := ground >> rewrite [headPtr_nil, lastPtr_nil, headPtr_cons,
    lastPtr_singleton, lastPtr_snoc] with self

example … := by
  iframe by sym => first ((simp slPure); finish) (simp slPure) (finish)
```
-/
syntax (name := iFrame) "iframe" (" by " tacticSeq)? : tactic

elab_rules : tactic
  | `(tactic| iframe $[by $tac?]?) => Tactic.focus do withMainContext do
  let discharger : Option Syntax.Tactic := tac?.map fun tac => ⟨tac.raw⟩
  let localAsms :=
    (← (← getLCtx).getAssumptions).map LocalDecl.fvarId |>.toArray
  let _ ← Aeneas.Simp.simpAt true
    { dsimp := false, failIfUnchanged := false, maxDischargeDepth := 1 }
    { hypsToUse := localAsms }
    (.targets #[] true)
  if !(← getGoals).isEmpty then
    let goal ← getMainGoal
    IFrame.solveGoal discharger goal
    replaceMainGoal []

/-- Normalize the separating conjunctions of the goal: float the existentials out of them, drop
the `emp`s, and reassociate to the right.

Also collapses a ramified wand whose antecedent is a pure equality
(`entails_postWand_pure_eq`): that is the shape a terminal return leaves behind, and
frame inference cannot cancel it on its own. -/
elab "isimp" : tactic => withMainContext do
  let _ ← Aeneas.Simp.simpAt true
    { dsimp := false, failIfUnchanged := false, maxDischargeDepth := 1 }
    { addSimpThms :=
        #[``sep_emp_l_eq, ``sep_emp_r_eq,
          ``sep_exists_l_eq, ``sep_exists_r_eq, ``sep_assoc_eq,
          ``entails_postWand_pure_eq] }
    (.targets #[] true)

end Aeneas.SepLogic
