(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [bitwise] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Bitwise.

(** [bitwise::shift_u32]:
    Source: 'tests/src/bitwise.rs', lines 4:0-4:31 *)
Definition shift_u32 (a : u32) : result u32 :=
  t <- u32_shr a 16%usize; u32_shl t 16%usize
.

(** [bitwise::shift_i32]:
    Source: 'tests/src/bitwise.rs', lines 11:0-11:31 *)
Definition shift_i32 (a : i32) : result i32 :=
  t <- i32_shr a 16%isize; i32_shl t 16%isize
.

(** [bitwise::xor_u32]:
    Source: 'tests/src/bitwise.rs', lines 18:0-18:37 *)
Definition xor_u32 (a : u32) (b : u32) : result u32 :=
  Ok (u32_xor a b).

(** [bitwise::or_u32]:
    Source: 'tests/src/bitwise.rs', lines 22:0-22:36 *)
Definition or_u32 (a : u32) (b : u32) : result u32 :=
  Ok (u32_or a b).

(** [bitwise::and_u32]:
    Source: 'tests/src/bitwise.rs', lines 26:0-26:37 *)
Definition and_u32 (a : u32) (b : u32) : result u32 :=
  Ok (u32_and a b).

End Bitwise.
