-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [betree_main]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Base
import BetreeMain.Types
open Primitives
open betree_main

/- [betree_main::betree_utils::load_internal_node] -/
axiom betree_utils.load_internal_node_fwd
  : U64 → State → Result (State × (betree.List (U64 × betree.Message)))

/- [betree_main::betree_utils::store_internal_node] -/
axiom betree_utils.store_internal_node_fwd
  :
  U64 → betree.List (U64 × betree.Message) → State → Result (State ×
    Unit)

/- [betree_main::betree_utils::load_leaf_node] -/
axiom betree_utils.load_leaf_node_fwd
  : U64 → State → Result (State × (betree.List (U64 × U64)))

/- [betree_main::betree_utils::store_leaf_node] -/
axiom betree_utils.store_leaf_node_fwd
  : U64 → betree.List (U64 × U64) → State → Result (State × Unit)

/- [core::option::Option::{0}::unwrap] -/
axiom core.option.Option.unwrap_fwd
  (T : Type) : Option T → State → Result (State × T)

