(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [hashmap]: type definitions *)
module Hashmap.Types
open Primitives

#set-options "--z3rlimit 50 --fuel 0 --ifuel 1"

(** [hashmap::List] *)
type list_t (t : Type0) =
| ListCons : usize -> t -> list_t t -> list_t t
| ListNil : list_t t

(** [hashmap::HashMap] *)
type hash_map_t (t : Type0) =
{
  hash_map_num_entries : usize;
  hash_map_max_load_factor : (usize & usize);
  hash_map_max_load : usize;
  hash_map_slots : vec (list_t t);
}

