(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [external]: external type declarations *)
module External.TypesExternal
open Primitives

#set-options "--z3rlimit 50 --fuel 1 --ifuel 1"

(** [core::cell::Cell]
    Source: '/rustc/ad963232d9b987d66a6f8e6ec4141f672b8b9900/library/core/src/cell.rs', lines 293:0-293:26
    Name pattern: core::cell::Cell *)
val core_cell_Cell_t (t : Type0) : Type0

(** The state type used in the state-error monad *)
val state : Type0

