(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [external]: external type declarations *)
module External.TypesExternal
open Primitives

#set-options "--z3rlimit 50 --fuel 1 --ifuel 1"

(** [core::num::nonzero::NonZeroU32]
    Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/core/src/num/nonzero.rs', lines 50:12-50:33
    Name pattern: core::num::nonzero::NonZeroU32 *)
val core_num_nonzero_NonZeroU32_t : Type0

(** The state type used in the state-error monad *)
val state : Type0

