(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [hashmap_main]: opaque function definitions *)
open primitivesLib divDefLib
open hashmapMain_TypesTheory

val _ = new_theory "hashmapMain_Opaque"


val _ = new_constant ("hashmap_utils_deserialize_fwd",
  “:state -> (state # u64 hashmap_hash_map_t) result”)

val _ = new_constant ("hashmap_utils_serialize_fwd",
  “:u64 hashmap_hash_map_t -> state -> (state # unit) result”)

val _ = export_theory ()
