on:
  push:
    branches-ignore: [ '_**' ]
  pull_request:
  workflow_dispatch:

jobs:
  nix:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, linux, nix]
    steps:
      #- uses: cachix/install-nix-action@v22
      - uses: actions/checkout@v4
      - run: nix build -L .#aeneas
      - run: nix build -L .#checks.x86_64-linux.aeneas-tests
      - run: nix build -L .#checks.x86_64-linux.aeneas-verify-fstar
      - run: nix build -L .#checks.x86_64-linux.aeneas-verify-coq
      #- run: nix build -L .#checks.x86_64-linux.aeneas-verify-lean
      - run: nix build -L .#checks.x86_64-linux.aeneas-verify-hol4
  lean: # Lean isn't supported by Nix, so we need to add extra steps
    runs-on: [ubuntu-latest]
    steps:
      # Install curl
      - run: sudo apt update && sudo apt install curl
      # Install Elan (https://leanprover-community.github.io/install/linux.html)
      - run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh
      #- run: sudo apt-get update && sudo apt-get install make
      # Verify
      - run: cd tests/lean && make
      #- run: cd tests/lean && lake build
