name: Deploy Aeneas user docs to GitHub pages

on:
  push:
    branches: [main]

jobs:
  select-runner:
    uses: ./.github/workflows/select-runner.yml

  build:
    needs: [select-runner]
    runs-on: ${{ fromJSON(needs.select-runner.outputs.runs_on) }}
    steps:
      - name: Install Nix
        if: ${{ runner.environment == 'github-hosted' }}
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-substituters = https://hacl.cachix.org
            extra-trusted-public-keys = hacl.cachix.org-1:FzsZ2xsByOwKwIWNPII7yMOelJNDZ12mDAj3d1eGX0c=
      - uses: actions/checkout@v4
      - run: nix build '.?dir=docs/user'#book
      - uses: actions/upload-pages-artifact@v3
        with:
          path: result/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
