-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [loops]: type definitions
import Base.Primitives

/- [loops::List] -/
inductive list_t (T : Type) :=
| Cons : T -> list_t T -> list_t T
| Nil : list_t T

